### ISSUE TITLE
Explain/remove 512 limit of tracestate in spec

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#109]
We have explanation of 512 limit in rationale file, but not in spec. Suggestion was [made](https://github.com/w3c/distributed-tracing/pull/107) to put it into spec.

**Comment by SergeyKanzhelev** [comment]
We explained in PR why we need limit. We still haven't explained why the limit is 512

**Comment by SergeyKanzhelev** [comment]
So far asking different providers - everybody wants smaller limit, but have not upper-bound physical limitation that will prevent saving and propagation of 512 characters.

So we need to put rationaly of why we need 512. If you implemented tracestate - can you post example/size you need?

**Comment by SergeyKanzhelev** [comment]
For example, B3 encoding will require 72 characters `tracestate: b3=80f198ee56343ba864fe8b2a57d3eff7-05e3ac9a4f6e3b90-1-e457b5a2e4d86bd1` (see: https://github.com/openzipkin/b3-propagation/issues/21).

**Comment by yurishkuro** [comment]
I feel that any limit number is going to be largely arbitrary. We can instead clearly outline procedure for trimming the state and not specify a hard limit, or use an external one like limit for cookies.

**Comment by SergeyKanzhelev** [comment]
One thing I think we can avoid by defining some hard limit is abuse of the header to propagate user-defined baggage. If you know that it will be cut anyway - you'd look for solution like `Correlation-Context` from the beginning instead of frustration when context will not be propagated,

I like that idea though. Definitely good idea to detail the trimming procedure

**Comment by yurishkuro** [comment]
I just think the exact limit can be very application specific, e.g. an application that exchanges many small messages will be more sensitive to the header size than one that carries 20Kb JSON requests. So the exact limit might be configurable per application, but the spec's hard limit should be more generous, like the cookie size limit of 4093.

Let the market forces pressure vendors to keep the size to a minimum.

**Comment by discostu105** [comment]
Here is how the Dynatrace tracestate will _likely_ (typically) look like:

`fw5-29a-3039@dt=1;FEC354CD6;1;2;727c` (36 bytes)

However, the elements are of variable length, so they could be longer. The theoretical maximum would be like this:

`fw5-ffffffff-ffffffff@dt=ffffffff;ffffffffffffffff;ffffffff;ffffffff;ffffffff` (77 bytes)

**Comment by SergeyKanzhelev** [comment]
Closing in favor of https://github.com/w3c/trace-context/issues/239
