### ISSUE TITLE
Do we need a sampling bit in trace-parent?

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#122]
**Issues**
* Most APM vendors will ignore the sampling bit.
* Sampling will drive costs with cloud provider.
* Semantics are not clearly defined. What should you do? Can you change it?
* How to handle system that do not upfront sampling?
* We cannot *force* third parties to trace a request. We can only *recommend* it. 
* Forcing downstream tracing might result in a DDoS attack.

**The problem to be solved**
Systems **cannot** be forced to trace a request. However, as different systems use different sampling rates we want to sync on important requests to increase the probability to sample the same trace and thus improve the probability for an end-to-end trace.

**Proposal**
Have a tracing bit be a _hint_ from the parent. The flag is supposed to have multiple values ordered in the following priority.

* Traced - Last hop of request is traced. (1)
* Undecided - Tracing data collection decision is deferred.  (2)
* Not traced - Last hop of request is not traced. (0)

Reasons why traces can be undecided:
* Injecting IDs in the first hop but not collecting a trace and not making a sampling decision
* A load balancer waiting for a request to return and deciding on whether to keep a trace.

We decided to use these values as they map with current implementations. 

**Beyond**
We also need a way to define that a certain request was requested to be traced (e.g. by the user for debugging). This should be a separate flag as it relates to the entire trace and not just to the last hop. This field also **must not** be modified. The proposal is to call the flag _requested-trace_. Examples are:

* user requested to trace a request from e.g. Chrome Dev Tools
* a synthetic test users want to collect end-to-end information for

**Comment by SergeyKanzhelev** [comment]
is it intentional that `Undecided` is `2`. With the `0` in a `Traced` bit? Not `3` with `1` in Traced bit?

**Comment by tylerbenson** [comment]
By calling it a sampling *bit*, that implies to me this is a bitfield, so I assume 3 would portray an odd notion of both sampled and undecided.
