### ISSUE TITLE
How and when are you allowed to restart a trace

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#146]
We discussed the need and option to restart a trace.  The question came up during test case generation. 

Key questions are: 
- When are you allowed to restart a trace?
- Do you also clear ```tracestate``` when you restart?
- Are there multiple types of restart?
  - Soft restart keeping tracestate
  - Hard restart not keeping tracestate

**Comment by SergeyKanzhelev** [comment]
I believe we discussed this topic many times and need to close on this. Perhaps add some rationale section on it. I believe specification already allows any of behaviors you listed. Even if spec says you MUST restart and clear `tracestate`, this specification allows to add all older `tracestate` entries. So both - "soft" and "hard" restarts are allowed. 

Also restart addresses privacy and security concerns. So we must allow restart at any moment.

I'll craft some rationale doc update talking about restart.
