### ISSUE TITLE
Integrate Timing Information in Trace-Context

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#149]

**Comment by yurishkuro** [comment]
timing of what?

**Comment by SergeyKanzhelev** [comment]
@yurishkuro here @AloisReitbauer mean some timing information that caller may send (like time passed from the begging of the call) so callee will store or propagate it. So UI can draw spans more accurate. The idea was to think how server timing headers concept may be used when sending data, not only in response headers.

We marked with the "future" milestone as this is theoretical for now.
