### ISSUE TITLE
which mailing list to use

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#152]
Readme refers to http://lists.w3.org/Archives/Public/public-trace-context/ when working group refer to
https://lists.w3.org/Archives/Public/public-trace-context-wg/

@wseltzer can we reuse mailing lists? Or move archives (not much to move, but nevertheless).

**Comment by plehegar** [comment]
We can reuse the mailing list. I'll close the CG and reassigns the mailing list to the WG if that's ok with everyone.

**Comment by SergeyKanzhelev** [comment]
@plehegar this would be the best

**Comment by yurishkuro** [comment]
Should the members of the community group rejoin the WG?

https://www.w3.org/2004/01/pp-impl/108594/instructions

**Comment by SergeyKanzhelev** [comment]
@plehegar can you help with Yuri's question?

**Comment by plehegar** [comment]
Yes, they should. If they are not W3C Members, they should reach out to Alois and me so we can sort things out.

**Comment by SergeyKanzhelev** [comment]
@plehegar the link on https://www.w3.org/2018/distributed-tracing/ still points to the different mailing list. Who owns working group page and how to edit it?

**Comment by wseltzer** [comment]
looks done to me.

**Comment by SergeyKanzhelev** [comment]
yep. Looks good now. Closing
