### ISSUE TITLE
Document procedures for spec changes

### ISSUE THREAD

**Issue by yurishkuro** [w3c/trace-context#165]
I propose we define a more formal process for making decisions that result in spec changes, to avoid issues like this: https://github.com/w3c/distributed-tracing/pull/142#issuecomment-415237146

Specifically:
- officially list tracing systems that are willing to implement the spec once finalized
- list official representatives for those systems who will vote on their behalf
- define voting rules, either super-majority or full consensus with a certain vote SLA (eg a week, after which you are considered abstained)
- require spec changes to be voted before merging

In-person/online meetings not attended by all representatives do not constitute a formal vote. They can be used for brainstorming and generating proposals with documented discussions of pros/cons.

If W3C already has alternative protocols for voting, we can use those, the main point is to hold formal votes in changes.

**Comment by AloisReitbauer** [comment]
I think this one can be closed given we have the updated contributing model.  https://github.com/w3c/distributed-tracing-wg/blob/master/CONTRIBUTING.md
