### ISSUE TITLE
Value format section is confusing

### ISSUE THREAD

**Issue by bogdandrutu** [w3c/trace-context#168]
Working to add support for the tracestate header, I found this to be confusing:
https://github.com/w3c/distributed-tracing/blob/master/trace_context/HTTP_HEADER_FORMAT.md#value-format

Main confusions:
* Do we always have to propagate the traceparent in the tracestate? Based on the examples this seems to be the case, but I think this should not be the default.
* Propagating the traceparent in the tracestate is a vendor specific implementation and probably should not be added in the public (official) examples. Every vendor can choice to do this based on their need, for example propagating only the span-id.

**Comment by AloisReitbauer** [comment]
This issue should be handled with the latest PR for the heder format

**Comment by SergeyKanzhelev** [comment]
this is addressed in #283
