### ISSUE TITLE
discuss where to place reference implementations

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#169]
We need to discuss where to place reference implementation for parsers

**Comment by yurishkuro** [comment]
I propose https://github.com/TraceContext. Also for the interop harness. Assuming @adriancole won't mind as he owns that org.

**Comment by bogdandrutu** [comment]
I am also one of the owners and I don't think @adriancole will mind.

**Comment by SergeyKanzhelev** [comment]
Any reason why not to put it in this repository? @plehegar what's the best practices in W3C?

**Comment by codefromthecrypt** [comment]
SGTM also it is co-owned by bogdan so he can add anyone else as well.

**Comment by AloisReitbauer** [comment]
We also have https://github.com/distributed-tracing where we have already put the examples. For me, this is the best place.

**Comment by plehegar** [comment]
I support using a separate repo for the reference implementation. You'll probably want to use a specific license for it and I'd need to be convinced before having W3C involved in that.

**Comment by SergeyKanzhelev** [comment]
Closing. Reference implementations will be implemented in separate repositories outside of W3C group.
