### ISSUE TITLE
What to do when empty tracestate?

### ISSUE THREAD

**Issue by bogdandrutu** [w3c/trace-context#171]
Some libraries like OpenCensus when used with exporters like Zipkin don't need a tracestate (or is empty).

Questions:
1) What is the correct behavior: a) don't send a tracestate header or b) send an empty tracestate header?

**Comment by reyang** [comment]
The current ABNF treats empty tracestate header as illegal.
Implementation should not send empty tracestate header.

**Comment by SergeyKanzhelev** [comment]
Fixed via #188
