### ISSUE TITLE
What to do when malformed headers are received?

### ISSUE THREAD

**Issue by bogdandrutu** [w3c/trace-context#172]
There are 2 questions here:
1) If traceparent is malformed does the implementation need to propagate the tracestate (if valid)?
2) If the tracestate is malformed does the implementation need to propagate the traceparent (if valid, and will do the necessary mutations like span_id)?

**Comment by AloisReitbauer** [comment]
For 1. I would definitely say, that we restart the trace and also reset the tracestate. 

For 2. I would propose to clear the tracestate but reuse the traceparent.

**Comment by rghetia** [comment]
Do we have consensus on what @AloisReitbauer has suggested?

**Comment by reyang** [comment]
During today's discussion, most of the attendees agreed with @AloisReitbauer's proposal.

https://github.com/w3c/distributed-tracing/blob/master/meeting_notes/2018-09-11.md#alois-how-to-treat-partially-corrupt-headers

**Comment by SergeyKanzhelev** [comment]
Fixed via #191
