### ISSUE TITLE
Action on tracestate header larger than 512 is confusing

### ISSUE THREAD

**Issue by rghetia** [w3c/trace-context#175]
According to spec at one place it says ignore it (I think it means drop it) and other place it says it is up to the tracer.

"The length of a combined header MUST be less than or equal to 512 bytes. If the length of a combined header is more than 512 bytes it SHOULD be ignored."

"If the tracestate value has more than 512 characters, the tracer CAN decide to forward the tracestate. When propagating tracestate with the excessive length - the assumption SHOULD be that the receiver will drop this header."

1. Which one should it be?
     a. Drop entirely
     b. forward the most recent up to  512 char.
     c. forward (512 has no meaning then)
2. If the received header is > 512 then should traceparent be dropped as well? Probably not. But clarification in the spec would be good.

**Comment by SergeyKanzhelev** [comment]
first statement is about parsing - second about propagation further after modification. It is totally not clear from spec - you are correct.

This concern should be resolved with @yurishkuro proposal here: https://github.com/w3c/distributed-tracing/issues/109

**Comment by SergeyKanzhelev** [comment]
Closing in favor of https://github.com/w3c/trace-context/issues/239
