### ISSUE TITLE
Change in example's tracestate value is confusing

### ISSUE THREAD

**Issue by sdboyer-stripe** [w3c/trace-context#181]
Hi! So glad you folks are working on this!

Reading over the spec, i noticed that the value for `congo` in `tracestate` changed in the second example under [section 2.1](https://w3c.github.io/distributed-tracing/report-trace-context.html#relationship-between-the-headers). ([line with changed value](https://github.com/w3c/distributed-tracing/blame/cc207fecda51cfc1e8d52cd93687bfbeeb36c352/trace_context/HTTP_HEADER_FORMAT.md#L24))

This change would seem to be at odds with the surrounding description; if values in `tracestate` are opaque, shouldn't that imply that the `rojo` system would not alter the value of `congo` in `tracestate`, instead propagating it forward?

**Comment by reyang** [comment]
Good catch.
