### ISSUE TITLE
Clarity on the definition of Span-id

### ISSUE THREAD

**Issue by chris-rogala** [w3c/trace-context#193]
It would be helpful to have the Span-id section, found here [https://w3c.github.io/distributed-tracing/report-trace-context.html#span-id](https://w3c.github.io/distributed-tracing/report-trace-context.html#span-id), a little more detailed out.  It would be more clear if span was a little more clearly defined.  While this could be inferred, it may be helpful to have a clear definition for what it means within this document.  Additionally, it would be helpful if examples were provided to provide direction on how the value could be generated.

**Comment by yurishkuro** [comment]
Do you have suggestions on how to define the span more clearly?  Do you have any specific questions about it?

**Comment by chris-rogala** [comment]
Personally, I am not certain what a Span-id is within this document.  I have inferred that it is a unique identifier to represent a single operation within a parent.  Is that a correct assumption?  If so, how do you recommend generating the span-id?  Should a cryptographic library be used to generate a random byte array?  Or is there an existing algorithm that can be used to construct it? 

I have read other articles, like this one [https://kamon.io/documentation/1.x/core/basics/tracing/](url), that state it contains information about it's parent as well as tags that describe it.  Articles like this invalidate my initial assumption.  

Any clarity you can provide would be greatly appreciated.

**Comment by yurishkuro** [comment]
I think this might be helpful for understanding the "span": https://github.com/opentracing/specification/blob/master/specification.md#the-opentracing-data-model

**Comment by chris-rogala** [comment]
I actually cloned one of the repos for OpenTracing earlier today, which assisted in my initial assumption of span.  That said, it also caused some confusion with respect to the optional parameters described.  In the tracer section, it talks of optional parameters:

- Zero or more references to related SpanContexts, including a shorthand for ChildOf and FollowsFrom reference types if possible.
- An optional explicit start timestamp; if omitted, the current walltime is used by default
- Zero or more tags

Are those parameter specific to the actual log entry or should they be part of the span-id.  I would assume they are simply part of the log entry since the size of the span-id is so small.  Correct?

My understand is the TraceParent field is intended to define a span.  The trace-id is groups the spans so they can be identified in a graph.  Is the span-id simply a random identifier for a single operation?  If so, should a cryptographic library be used to generate the value?

**Comment by yurishkuro** [comment]
> Is the span-id simply a random identifier for a single operation? 

Yes.

> If so, should a cryptographic library be used to generate the value?

You can, but it's not a requirement. Many tracers simply use the std random number generator in the language. Clashes among trace and span IDs do happen though, and mess up a small percentage of the data.

**Comment by chris-rogala** [comment]
With that knowledge, I would recommend the following modifications:

The Span-id is a random identifier for a single operation within a parent.  The Span-id MUST not reuse a Span-id received.  The generation of the Span-id SHOULD use process to reduce collisions with other Span-ids generated within the trace.  

The key points in the draft would include:
1) It SHOULD not be reused
2) It SHOULD be generated for each operation
3) The process to generate the Span-Id SHOULD utilize a process that reduces collisions/duplicates

Thoughts?

**Comment by basvanbeek** [comment]
There are tracing systems that create so called shared spans, Zipkin being one of them. In this case an instrumented client can share the same SpanContext (thus also the same spanid) with its instrumented server counterpart. I find these suggestions rather adding confusion then taking them away. I question the need to iron out a very precise definition of spanid which might just constrain and handicap us or even worse having people assume things that are incorrect. We're dealing with different tracing implementations here that might expect / need some wiggle room.

**Comment by chris-rogala** [comment]
The use of SHOULD allows the wiggle room.  If it is okay to share the spanid across systems, then I would find it helpful for this to be described in the documentation.  Not having it, leaves it to the implementer to make assumptions which could cause issues with interoperability.  Adding some clarity around how the spanid should be created/used with potential best practices would help to eliminate assumptions.

**Comment by SergeyKanzhelev** [comment]
There is no mention of `Span` in spec any longer. Should it be closed or there is more to discuss?

**Comment by chris-rogala** [comment]
I think we can.  There is still a reference to span in the 2.2.2.2 Parent-id section but it is clear now.
