### ISSUE TITLE
Trace-id and Span-id - What makes up valid bytes?

### ISSUE THREAD

**Issue by chris-rogala** [w3c/trace-context#194]
In the [https://github.com/w3c/distributed-tracing/blob/master/trace_context/HTTP_HEADER_FORMAT.md#trace-id](https://github.com/w3c/distributed-tracing/blob/master/trace_context/HTTP_HEADER_FORMAT.md#trace-id) section, it states 

> All bytes 0 are considered invalid.

What does that mean?  Does that mean that '00' is invalid?  Does that mean an array length of 0 is invalid?

In the third paragraph the example:

> Instead of setting trace-id value to 0000000000000003ce929d0e0e4736 it is recommended to generate a value like 4bf92f3577b34da6a3ce929d0e0e4736 where 4bf92f3577b34da6a is a random value or a function of time & host value. 

If 00 is invalid, then the leading zeros would be invalid instead of not recommended.  

I have the same question in Span-id section.

> All bytes 0 is considered invalid.
 
Thank you in advance.

**Comment by reyang** [comment]
@chris-rogala it means 00000000000000000000000000000000 is an invalid trace_id, and 0000000000000000 is an invalid span_id.

https://github.com/w3c/distributed-tracing/blob/master/test/test.py#L263

Probably we want to change the wording to make it easier to understand? @SergeyKanzhelev

**Comment by SergeyKanzhelev** [comment]
closed via #257
