### ISSUE TITLE
Question on test-harness cases around invalid tracestate

### ISSUE THREAD

**Issue by discostu105** [w3c/trace-context#195]
I've updated our implementation to pass almost all current test-cases, except for these:

    test_tracestate_member_count_limit
    test_tracestate_key_length_limit
    test_tracestate_key_illegal_vendor_format
    test_tracestate_key_illegal_characters
    test_tracestate_duplicated_keys

My struggle with these test-cases is that they require full parsing of tracestate. In my current C++ based implementation, I just find the position of our tracestate-entry and keep the "rest" of tracestate (before and after string) untouched.

Now, although it would be an interesting exercise to implement this algorithm as efficiently as possible (single-pass, allocation-free), I want to ask the more general question, if an implementer really needs to enforce all spec rules strictly like this and _reject_ a tracestate at violation? Of course an implementer must not produce data that violates the spec, but must it really check it all? Also, technically, I believe while the spec gives these requirements, but it does not say that a trace must be restarted if a violations happens (please correct me if that's wrong!).

Also: Are we going to assign a certain "badge" / "certification" to certain vendors if their implementation passes 100% tests? What does it mean? What if an implementer decides not to implement certain checks for said reasons?

**Comment by discostu105** [comment]
We have discussed this today at W3C working group (see notes https://docs.google.com/document/d/12yecf7L1uibMIGP_YkTRM-KKCZZkluqmYqXxGFHD5J4/edit#).

We discussed not having theses verification tests mandatory. An implementer should only try to extract their own tracestate part. If that fails, optionally discard the whole tracestate, otherwise keep propagating the rest of the tracestate.

@SergeyKanzhelev , @reyang : what you do think?

**Comment by reyang** [comment]
@discostu105 thanks for the updates!

I agree with the general rule _An implementer should only try to extract their own tracestate part. If that fails, optionally discard the whole tracestate, otherwise keep propagating the rest of the tracestate._ Let's
follow up in Pull Requests and discuss the details.

**Comment by SergeyKanzhelev** [comment]
@reyang do we have categories supported by infra? We can mark these tests with the special "StrictValidation" category.

**Comment by reyang** [comment]
@SergeyKanzhelev yes we can tag the test cases.

Do we want to update the spec first, or we don't want to define "StrictValidation" in the spec?

**Comment by SergeyKanzhelev** [comment]
hm. Yes. spec is vague about parsing issues in `tracestate`. Perhaps some clarification is required. As a first step simply marking tests will be a good first step.

**Comment by reyang** [comment]
I've added a STRICT_LEVEL environment variable, and we can use it to tag the test cases for different level of strictness. @discostu105 @SergeyKanzhelev We should discuss which test cases belong to which level.

**Comment by reyang** [comment]
@discostu105 please refer to https://github.com/w3c/trace-context/blob/master/test/test.py#L710 and put the existing test cases into different strictness levels.
