### ISSUE TITLE
Special character between trace context fieds

### ISSUE THREAD

**Issue by bogdandrutu** [w3c/trace-context#2]
One of the request was to add an extra human-readable character between the trace context fields. The current proposal was to not have this extra character.

Proposal to use '-' character between version/trace_id/span_id/options:
`Value = 00-4bf92f3577b34da6a3ce929d0e0e4736-00f067aa0ba902b7-01000000`

This proposal will allow SREs to easily copy-paste or parse the trace-id/span-id/options if needed.

**Comment by wu-sheng** [comment]
In skywalking, we use '|' to split right now. Here is a sample context:
```
trace_id_A|100|REMOTE_APP|10.2.3.16:8080|Trace.global.id.123|1
```

**trace_id** and **Trace.global.id** include '.' and '-' , and that is why we choice '|' at first place.

**Comment by wu-sheng** [comment]
We definitely can support this with tiny changes, after this spec is settled and people can get benefits from these changes.

**Comment by AloisReitbauer** [comment]
This issue is really old. Should we mark it as resolved?

**Comment by SergeyKanzhelev** [comment]
Agree needs to be resolved. I'll close it for now
