### ISSUE TITLE
Replace "span" nomenclature

### ISSUE THREAD

**Issue by yurishkuro** [w3c/trace-context#205]
We are using the term "span-id" in the `Traceparent`, but not all tracing systems are built around span model, e.g. X-Trace and Canopy (and probably SolarWinds, if they kept their roots) are built around event model, which is considered more expressive than the span model. I don't think anything in the spec actually _requires_ the model to be span-based, and passing the ID of the `happened-before` "thing" should work for both types of trace models.

**Proposal**: replace references to "span-id" with "parent-id".

NB: "parent" isn't great either, but the header is already called Traceparent, so the boat has sailed on that.

Incidentally, this might address questions like #204.

**Comment by SergeyKanzhelev** [comment]
what about `request-id`? Will it be more confusing?

**Comment by yurishkuro** [comment]
yes, I think it would be more confusing. I have seen people propagating and logging request-id as an equivalent of trace-id, so it can be misinterpreted as "distributed request id" vs. "single RPC request id".

**Comment by SergeyKanzhelev** [comment]
reference to RPC made me think that `call-id` may be another alternative. However out of all replacements `parent-id` is probably the best name. First, it matched the header name. Second it indicates a difference between caller and callee. Discussing AMQP we realized that `message-id` header defined by AMQP refers to individual message, and semantically not the same as `traceparent`. Message id can be used to dedup messages on the server when `traceparent` only defines the source this message came from. Perhaps all those considerations can be mentioned in rationale doc

**Comment by yurishkuro** [comment]
I think we also want to avoid locking ourselves into the RPC nomenclature. Even though the current spec is for an http headers, most tracing libs today use the same names and format across different transports, e.g. queues, where terms like "call" don't apply.

**Comment by AloisReitbauer** [comment]
I also vote for parent-id.  request-id for me refers more to an end-to-end request. Caller-id feels wrong for pub/sub systems.

**Comment by falenn** [comment]
I agree, also with the rename.  I also like the AMQP juxtaposition.  In my mind, message-driven architectures are characterized more as state moving through services - the message is more akin to the trace, the interactions from service to service are spans.  Composite services in the flow may call other services causing child-spans - now a blend of req/resp and messaging architectures, all correlating to the same trace.  Thoughts?

**Comment by cce** [comment]
Forgot to reply while at a conference last week, but thanks for mentioning us @yurishkuro! We do still use event IDs everywhere instead of span IDs at SolarWinds in AppOptics. However we also have been adapting more internally to co-exist event IDs with span IDs in our support for span-based OSS tracing standards (basically we assign span IDs as the first event ID of the logical span).

**Comment by SergeyKanzhelev** [comment]
@cce just to confirm - you don't have any concerns with the `parent-id`, do you? It is just a name that clarifies an intent and semantics of the field in the spec
