### ISSUE TITLE
Privacy risk if trace context is used as response headers in cross-origin calls

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#209]
During the privacy review suggestion was made to explicitly mention potential privacy risk of returning trace context headers in cross-origin calls.

**Comment by plehegar** [comment]
Relevant notes from the call:
[[
@npdoty : if headers are sent in HTTP responses, or expected to persist across http request and response pairs, there are potential cross-origin privacy implications

@SergeyKanzhelev : […] We have use for that. wg doesn't feel like it's used in the same way, so we didn't spec it.

@npdoty : i think would create more concerns we: cross-origin tracking, if we expect same identifier to be persisted between. it could violate assumptions we have about privacy model, if browser will take identifier from one party and send to another.

@SergeyKanzhelev : we could explain that.
]]
https://www.w3.org/2018/11/29-privacy-minutes.html#item00

**Comment by SergeyKanzhelev** [comment]
I propose to move this issue to PR milestone. I'm sending PR just in case we want to merge it now

**Comment by SergeyKanzhelev** [comment]
this was addressed in #258
