### ISSUE TITLE
Can a tracer/application only carry trace-parent and drop trace-state?

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#218]
This question came up during a discussion with AWS. What if a tracer or application has only limited bandwidth available and cannot forward more payload than the traceparent? Can trace-state be silently dropped? Propagating Trace parent alone still would add value for future correlation. 

Alternatively we can define a smaller minimal trace-state size that MUST be forwarded - e.g. 8 bytes for the parent tools trace parent. This will ensure that even when no detailed tracing data can be collected, the parent tracer can put the trace in the proper position in the trace tree.

**Comment by SergeyKanzhelev** [comment]
Closing in favor of https://github.com/w3c/trace-context/issues/239
