### ISSUE TITLE
Support for a type property of a Correlation Context value

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#22]
Some tracing vendors support types for the context properties. We can add `type` property to allow an explicit type specification. Something like this:

### Boolean
 
Binary flag. Supported values `1` for true and `0` for false.
 
**Examples**:
 
```
IsAuthenticated=1;type=bool
IsAuthenticated=0;type=bool
```
 
### Number
 
Numeric value as described in IEEE 754-2008 binary64 (double precision) numbers [IEEE754](https://en.wikipedia.org/wiki/Double-precision_floating-point_format).
 
**Examples**:
 
```
ExposurePercentage=33.33;type=number
Step=10;type=number
```

**Comment by bogdandrutu** [comment]
I would vote for some types (here wearing my OpenCensus hat):
* Integer (int64)
* Boolean

**Comment by wu-sheng** [comment]
Inside skywalking, with or without type works with it. In the head, only have string/int32(id represents string), but we add a `#` before the first char of string.

**Comment by SergeyKanzhelev** [comment]
@wu-sheng would `type` work than? Or you fine to assume the type without explicit specification? I don't think it's a good idea to hardcode `#` prefix as no other tools will understand it.

**Comment by wu-sheng** [comment]
@SergeyKanzhelev `type` is OK. I use that because skywalking want to keep the head as short as possible, to reduce the network payload. And this is a private protocol :) Easy to understand doesn't used to be the primary goal.

**Comment by SergeyKanzhelev** [comment]
moved to Correlation-Context repo.
