### ISSUE TITLE
Enable Rewrap or similar solution to limit the line width and simplify reviews

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#228]
Fixing line width makes it easier to review as comments associated with the line of code. So for long paragraphs it's easier to narrow down the comment.

There are many solutions to help with that. For VSCore [Rewrap](https://github.com/stkb/Rewrap) can be used.

**Comment by yurishkuro** [comment]
+1

but rather than IDE plugin (which are all different), I'd recommend a script, like https://prettier.io, which will produce the same results for everyone.

**Comment by SergeyKanzhelev** [comment]
Do you suggest to run script as part of CI somehow? How else this can be enforced?

**Comment by yurishkuro** [comment]
just like with Go code:
  * `make fmt` applies the formatting
  * `make lint` runs the formatter in readonly / fail-only mode
  * CI includes a step that run `make lint` and blocks the PRs on failure

Prettier is Node.js app, kinda pain to install on every run or locally, would be better to run it from a Docker image.

**Comment by SergeyKanzhelev** [comment]
I like the approach but I don't think it's reasonable to ask everybody to run those scripts locally. Have you tried VS Code extension? Is it working reliably?

**Comment by yurishkuro** [comment]
Why is unreasonable?  We require it for all PRs to Jaeger code base, for example. It's just one step, `make fmt` before you commit. If you forget, the CI fails.

**Comment by SergeyKanzhelev** [comment]
I'd be fine with this requirement (given I need to try how opinionated that thing is for markdown). I worry there may be a few contributors who doesn't use dev environment to contribute. Let's wait for more opinions

**Comment by danielkhan** [comment]
I just fixed the line lengths of one of my edits.
The tooling I used was:
- Visual Studio Code
- 'Markdown All in One' Extension with the following setting to enable line wrap validation:
```js
"markdownlint.config": {
  "MD013": true
},
``` 
- Setting `"editor.rulers": [80,120]`

This helps while editing.

We could additionally add markdownlint to the CI to enforce the rules.
This would make sure that the formatting is consistent without being too intrusive.

**Comment by AloisReitbauer** [comment]
I propose we have an editing guide where we define best practices and ideally tools. I just don't want to be forced to use any specific tool.  What about an editing guidelines doc?

**Comment by AloisReitbauer** [comment]
@SergeyKanzhelev  when you file an issue or PR please mark yourself as the owner. Otherwise, it is unclear who drives issues to resolution.

**Comment by yurishkuro** [comment]
@AloisReitbauer I am not a believer in the effectiveness of unenforced guidelines. I agree with you about forcing a specific tool like VSCode plugin on people. Having a guideline that is enforced by a linter at CI ensures that the guidelines are actually followed, and it does not get in the way of dev process.

Having said that, it's also annoying when the linter fails too late in the CI pipeline on something that could've been easily fixed by a tool, like a trailing space or unwrapped sentence. Which is why I am en even bigger proponent of auto-formatters (like `go fmt`).

**Comment by danielkhan** [comment]
Personally, I am not a big fan of automated code changes after a commit. Local tooling (chosen by everyone individually) can make sure that the linting rules are followed. This avoids failures on a commit for the most part.

**Comment by danielkhan** [comment]
As discussed in meeting 2019-01-15, we will for now just require 80 characters max line length.
We should add this to https://github.com/w3c/trace-context/blob/master/CONTRIBUTING.md

**Comment by nikmd23** [comment]
The [EditorConfig](https://editorconfig.org/) folks are [thinking about making line length a setting](https://github.com/editorconfig/editorconfig/wiki/Property-research:-maximum-line-length). If/Once they add that, we can simply drop a `.editorconfig` file in the repo and most text editors will enforce this for us.

**Comment by SergeyKanzhelev** [comment]
this is done in #282. We can create a new issue if we will see that note added and some config settings for vscode is not an adequate amount of details for this problem and we need more formal validators
