### ISSUE TITLE
One level down correlation context propagation (TTL=1)

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#23]
`TTL` property can be used by vendor to specify the short-living values. Examples may be component name that initiated the request. Such property should not be passed further than the first hop.

**Comment by wu-sheng** [comment]
I have discuss with @adriancole with the `TTL` value meaning, which is new to me :)  And I am curious about in which case, TTL > 1, and also make sense.  Can you give me some example? Thanks.

**Comment by SergeyKanzhelev** [comment]
`Trace-Id` is a perfect example of something that can be stored forever. Another example. When service receives the request and want to set the `userName` context property that will be associated with every span in the distributed trace `TTL` will be infinity. Which I'd suggest to be a default value.

In MS spec for this header we suggest it to be treated as read only so once the property is set - it is set forever. However it made us invent another header to propagate `TTL=1` context properties (caller and callee parameters).

**Comment by SergeyKanzhelev** [comment]
Please disregard my reply. I got the question now. I’ll reply when will get to computer

**Comment by SergeyKanzhelev** [comment]
@wu-sheng I agree - it's hard to come up with the good example of higher TTL. In fact we are using two separate headers - one for entire trace context and one for request AND response context. I know that many people just reuse a single context header and override values in it. Thus it may be a good idea to provide a mechanism to indicate that specific property is for immediate consumption only.

I thought TTL may be a useful concept when you are using some sort of service mesh layer for communication and want to force it to propagate your property further (TTL = 2).

Higher TTL may be used to propagate some sort of "deep investigation" flag. As a safeguard for not overflooding the storage with telemetry. Something like "trace a LOT, but only 5 layers down". Or "next 5 layers - return details of your execution to caller".

In reality the most important scenario for me is TTL=1 or alternative way to propagate caller/callee-only
properties like application name.

**Comment by codefromthecrypt** [comment]
I can't think of a better name, but we might. In the mean time we can refer
to this concept as ttl=1 and find/replace later.

This is highly important property as it impacts how brown field can work,
too. For example, propagating vendor-specific span info where the vendor is
likely on the other side. Like naver pinpoint next async id. If
intermediary tosses other headers and this is the only way, I think it will
be used for this.

**Comment by wu-sheng** [comment]
@SergeyKanzhelev Since you mentioned service mesh, maybe we can discuss more about this in service mesh case. For an application developer, you likely don't care about using linkerd(example) or not, right? So
- For manual instrumentation, how does the developer do?
- For auto agent, you have nothing to do... they do all by themself.

I think even for service mesh, you can't know when should set TTL > 1 in most cases.

I think this may be possible, but only for business tracing system, rather then system like most APM and tracer did.
> Higher TTL may be used to propagate some sort of "deep investigation" flag. As a safeguard for not overflooding the storage with telemetry. Something like "trace a LOT, but only 5 layers down". Or "next 5 layers - return details of your execution to caller".

**Comment by SergeyKanzhelev** [comment]
OK, I renamed the issue to indicate that in reality we only need one level down propagation.

There are two options:
- property on the items in correlation context collection
- separate header (call it `Request-Context`)

Second option can be better as you can pass this additional header both ways - with the request and with response. So two components can exchange identity and immediate context information.

Do you think an extra header is an OK option?

**Comment by wu-sheng** [comment]
@SergeyKanzhelev I have saw #39 . But what is the gap between it and `Correlation Context`. In my thought, `Correlation Context` means TTL=1, but seem you think otherwise. Can you explain more?

**Comment by SergeyKanzhelev** [comment]
`TTL=1` means the value will expire right away. Basically it's parent's context that will not be valid if one will propagate it further. Like caller's identity - application name or computer name. `Correlation-Context` in turn is about the entire trace.

**Comment by yurishkuro** [comment]
@wu-sheng I think `Correlation-Context` is meant to be "forever", not TTL=1.

**Comment by SergeyKanzhelev** [comment]
@yurishkuro confusion comes from the fact that service is not obligated to propagate `Correlation-Context`. It should make the best effort doing it, but the language is not `MUST`. This is how the limit on size was lifted quite high.

**Comment by SergeyKanzhelev** [comment]
Moved to Correlation-context repository
