### ISSUE TITLE
Decide, if 'generic tracer' should be mentioned in intro example

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#233]
In https://github.com/w3c/trace-context/blame/cr--edit-processing-model/spec/20-HTTP_HEADER_FORMAT.md#L37 we discuss the 'generic tracing system' that is only mentioned once in the rationale doc. Is this information really needed or too much of an implementational detail?

**Comment by AloisReitbauer** [comment]
I don't know what a generic tracer is supposed to be. I assume it refers to a tracer that does not use trace-state.  Is there any value in introducing the concept of a generic tracer?

**Comment by danielkhan** [comment]
Will remove
