### ISSUE TITLE
Decide, if reuse of last trace ID in traceparent needs to be mentioned in spec

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#234]
In https://github.com/w3c/trace-context/blame/cr--edit-processing-model/spec/20-HTTP_HEADER_FORMAT.md#L51 we mention the reuse of the last trace ID in traceparent.
This looks like an implementation detail and we should discuss if this should go into the spec.

**Comment by SergeyKanzhelev** [comment]
It was mentioned by @bogdandrutu in https://github.com/w3c/trace-context/issues/168. Suggestion was to remove `trace-id` from examples of `tracestate` entries to minimize the confusion

**Comment by AloisReitbauer** [comment]
I agree to not discuss trace-i in the context of trace-state. It is confusing
