### ISSUE TITLE
Decide, if we have to suggest an intrinsic format of trace-id

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#235]
In https://github.com/w3c/trace-context/blame/cr--edit-processing-model/spec/20-HTTP_HEADER_FORMAT.md#L105 we suggest that the random part should go on the right side to simplify sampling decisions.
Is this something that should go into the spec?

**Comment by AloisReitbauer** [comment]
We should tell people that they should strive for maximum randomness. Add note that implementations should look into the randomness of their IDs

**Comment by yurishkuro** [comment]
also that when you receive an inbound trace ID, you cannot make assumptions that some bits of it are more random than others.

**Comment by danielkhan** [comment]
In our meeting on 2019-01-15 it was agreed that the wording should be trimmed down to just advice implementors to ensure randomness of the ID and not encode any information.
A randomness as of UUIDv4 is deemed to be good enough.
