### ISSUE TITLE
Section on Recorded flag should be shorter and more precise

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#237]
In https://github.com/w3c/trace-context/blob/master/spec/20-http_header_format.md#recorded-flag-00000001 we describe the semantics of the recorded flag. 
It seems as if this paragraph reflects the long discussions and how unclear we are on its use case. We should come up with a clear description on its meaning and how to handle it without mentioning all corner cases if possible.

**Comment by AloisReitbauer** [comment]
Let us take semantics out and explain requirements what needs to be exchanged between systems in intro session.

**Comment by SergeyKanzhelev** [comment]
should this issue be in CR or PR is fine? Looks like editorial issue without actual impact on spec

**Comment by danielkhan** [comment]
To me the explanation we have now left room for ambiguity and I'd be in favor of sorting this out for the CR.

**Comment by mtwo** [comment]
Decision from meeting: we will push this back to the later milestone. This section is readable and implementable and we can try to shrink its size later.

**Comment by danielkhan** [comment]
This is a duplicate to #303 now
