### ISSUE TITLE
Decide, if we should explain OWS though we refer to the spec where it's defined

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#238]
In https://github.com/w3c/trace-context/blame/cr--edit-processing-model/spec/20-HTTP_HEADER_FORMAT.md#L312 we describe optional whitespace OWS though we refer to RFC7230 before. Should we replicate other specs in our spec or is the link sufficient?

**Comment by SergeyKanzhelev** [comment]
I think original spec has more wording on rationale of having OWS and how systems MAY decide to behave to increase readability when needed. All the text can be copy/pasted, but linking original may be an OK solution.

**Comment by AloisReitbauer** [comment]
I think we should remove duplicate definitions when we already reference the original source. We just need to make sure we reference the proper version. 

The old version for me was way TMI and confusing. Maybe a simple example could do the trick?

**Comment by AloisReitbauer** [comment]
We can duplicate what dictionary uses for a short description.
