### ISSUE TITLE
Header limits are obsolete and should be removed

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#239]
In https://github.com/w3c/trace-context/blame/cr--edit-processing-model/spec/20-HTTP_HEADER_FORMAT.md#L387 we describe the limits which still reflects the 512 character limit we agreed on before coming up with the 5 entry limit.
This is now described in https://github.com/w3c/trace-context/blame/cr--edit-processing-model/spec/20-HTTP_HEADER_FORMAT.md#L375
Should we remove the limits paragraph entirely?

**Comment by SergeyKanzhelev** [comment]
Is it possible to close on this item separately from the big CR PR? Few considerations:

- Rationale doc should be updated with the discussions and reasoning
- There are two items that we need to make sure to address https://github.com/w3c/trace-context/issues/175 and https://github.com/w3c/trace-context/issues/109
- My understanding that the `MUST propagate 5` thing is still too aggressive of a requirement (Maybe even more aggressive than limiting to 512 characters if there are abuse. At least this is what we discussed in Amazon office during the KubeCon and should re-hash in rationale doc again.). Discussion was that SaaS/platform vendor may have its own limit published, which will make an incentive for tracing vendors to limit `tracestate` entries they require. Basically follow the @yurishkuro suggestion in #109

**Comment by danielkhan** [comment]
ok - let's discuss that independently of the PR.

**Comment by AloisReitbauer** [comment]
We cannot move to PR if we do not reach a decision on this topic. I propose we add the trimming procedure to the PR and add a note that size requirements are still under discussion. What is currently in the spec does not reflect the latest discussions, so it at least needs to be removed.

**Comment by SergeyKanzhelev** [comment]
Let's clean up duplicates:

- [Can a tracer/application only carry trace-parent and drop trace-state?](https://github.com/w3c/trace-context/issues/218)
- [Explain/remove 512 limit of tracestate in spec](https://github.com/w3c/trace-context/issues/109)
- [Action on tracestate header larger than 512 is confusing](https://github.com/w3c/trace-context/issues/175)

Basically, we need to update rationale document with the logic of
decision and discussions we had. Suggest truncation strategies and
advice on the limits.

I'll close issues above. I'll sent a proposed update for this limit.

**Comment by danielkhan** [comment]
Let's continue discussion in #248

**Comment by danielkhan** [comment]
Let's continue discussion in #248

**Comment by SergeyKanzhelev** [comment]
@danielkhan can we keep the issue open as it's easier to discover issues left for CR than find a PR with the issue that wasn't closed.

**Comment by SergeyKanzhelev** [comment]
closed via #248
