### ISSUE TITLE
Mark "Other Protocols" section non-formative and simply point to the registry

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#247]
Section https://w3c.github.io/trace-context/#other-protocols is going to be updated and changed going forward as new protocols got supported.

@plehegar what's a good practice here? Have a link to a folder of specs with other protocols (like a GitHub link) or mark section as non-formative and update it even after spec was marked CR? Any other options here?

**Comment by nikmd23** [comment]
@plehegar has suggested that the spec link to a separate "registry" document, that can be updated more easily.

So essentially, the spec links to a separate document that is a "note". That note will link to other protocols. 

This makes sense to me, and allows us to provide guidance on other protocols without churning the spec or dealing with the W3C processes.

**Comment by AloisReitbauer** [comment]
LGTM

**Comment by plehegar** [comment]
Here is an initial draft: https://w3c.github.io/trace-context-protocols-registry/

**Comment by danielkhan** [comment]
LGTM

**Comment by nikmd23** [comment]
Thanks @plehegar. That looks great. Should we close this issue in favor of #254? @SergeyKanzhelev has listed out the work required to complete the registry there.
