### ISSUE TITLE
Should we allow modifying tracestate without changing traceparent?

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#250]
I think processing mode with only `tracestate` modification should be a valid case. It may be privacy-enforcing proxy or proxy that adds information about itself without touching `traceparent`. Like (potentially) service mesh scenario.

_Originally posted by @SergeyKanzhelev in https://github.com/w3c/trace-context/pull/222_

**Comment by nikmd23** [comment]
Agreed. 😄

**Comment by danielkhan** [comment]
This should be reopened because it is right now linked in the spec to track the discussion on this issue.

**Comment by SergeyKanzhelev** [comment]
@danielkhan I thought we had a discussion and decided there are valid scenarios for this. Do you want to re-open discussion?
