### ISSUE TITLE
What should we do when we restart a trace

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#252]
In case you are restarting a trace you should record the old traceparent. We have not really defined this behaviour

_Originally posted by @AloisReitbauer in https://github.com/w3c/trace-context/pull/222/review_comment/create_

**Comment by bogdandrutu** [comment]
I don't think this belongs to this project scope.

**Comment by nikmd23** [comment]
Is it safe to assume that the "restarter" of the trace would have to handle that in whatever way makes sense for them? Perhaps that's stuffing something into tracestate, perhaps it's emitting a "bridge" telemetry item - or something else entirely.

**Comment by AloisReitbauer** [comment]
I believe we have to define restarting a trace as creating a new trace-parent and clearing trace-state. If we would not clear trace-state this might have weird effects for a tracer b/c suddenly the traceid changed unexpectedly or may seem invalid.

**Comment by SergeyKanzhelev** [comment]
@AloisReitbauer there are many cases when restart of a trace may be needed. Some implementation may need to restart trace for internal propagation and recover to original trace when going back to external services. We can recommend certain implementations in blog posts or reference implementations. But I don't think restricting one or another behavior should be part of a spec.

Furthermore, this is not the completely blocking factor, but it is important nore. This behavior is hard to test using the test harness to ensure compliance.

**Comment by SergeyKanzhelev** [comment]
Discussion diverged from the originally posed "record all `traceparent`" proposal to discussion of this issue: https://github.com/w3c/trace-context/issues/146 

I think originally proposed recording of all `traceparent` is out of scope of a spec. Clearing the `tracestate` can be discussed separately. 

I vote for closing this issue as out of scope and keep #146
