### ISSUE TITLE
'Recorded' flag should be renamed in sampled flag

### ISSUE THREAD

**Issue by danielkhan** [w3c/trace-context#265]
As suggested by @yurishkuro in meeting 2019-03-13: The industry term is 'Sampled' and we should stick to that.

**Comment by codefromthecrypt** [comment]
note that the semantics have been changed from de facto sampled a loong time ago. renaming this to a term, but using it differently might be good or confusion causing. it would be better to revert the revert in the process of this, but I suspect people still don't care to make this match defacto https://github.com/w3c/trace-context/pull/142#issuecomment-415237146

**Comment by felixbarny** [comment]
What are the semantic differences between recorded and sampled? I thought this was just naming.

**Comment by codefromthecrypt** [comment]
On Wed, Apr 24, 2019 at 3:14 PM Felix Barnsteiner <notifications@github.com>
wrote:

> What are the semantic differences between recorded and sampled? I thought
> this was just naming.
>

https://github.com/w3c/trace-context/blob/master/spec/20-http_header_format.md#recorded-flag-00000001

the text wanders around suggesting there is no defined means of what
recorded aka sampled means, when clearly there has been significant
precendent for a trace scoped sampling decision. the text will take you a
while to read and I'd be surprised if you finished feeling you know what
this will do. Take this in comparison with the b3 text

https://github.com/apache/incubator-zipkin-b3-propagation#sampling-state

**Comment by yurishkuro** [comment]
The issue is that w3c spec is trying to squeeze a trinary state into one bit, a theoretical impossibility. It is also trying to accommodate tail-based sampling systems, which in practice don't need the propagation of sampling decision at all. I'd suggest that this section needs another design pass, not just a rename.

**Comment by danielkhan** [comment]
Done in #302
