### ISSUE TITLE
Add more editors for the document and add credits section

### ISSUE THREAD

**Issue by SergeyKanzhelev** [w3c/trace-context#268]
As we closing up on CR for the spec I think we need to expand the list of editors for the spec as we had. Please nominate people who you believe needs to be in the list.

@plehegar, is there any common practice on how to add CREDITS section to the spec?

**Comment by SergeyKanzhelev** [comment]
I clearly forgetting people, so please comment on this issue. I nominate the following (alphabetical order). 

Update: Please confirm yourself in the list. Feel free to send e-mail to me.

Editors:
- [x] @bogdandrutu 
- [x] @nikmd23 
- [x] @yurishkuro

For credits section:
- [x] @adriancole Adrian Cole 
- [x] @CodingFabian Fabian Lange
- [x] @danielkhan Daniel Khan
- [x] @discostu105 Christoph Neumüller
- [x] @erabug Erika Arnold
- [x] @mwear Matthew Wear
- [x] @reyang Reiley Yang
- [x] @tedsuo Ted Young
- [x] @tylerbenson Tyler Benson
- [x] @victorNewRelic Victor Soares

**Comment by tylerbenson** [comment]
I’ve been quiet lately, but I’ve been involved in the past.

**Comment by codefromthecrypt** [comment]
I think the nominees should ack before being added to any credits/marketing materials.

I don't want to be listed as there have been troubling technical change I don't want to be associated with. I don't want to re-elaborate this point.

**Comment by SergeyKanzhelev** [comment]
@adriancole thank you. I didn't try to be pushy. Added a note for people to confirm themselves. This spec got a lot of support from many people in different forms. And it will be fair to give credits.

**Comment by CodingFabian** [comment]
Despite not having followed recent evolution I am behind the effort and look forward to spend more time on this again. Thanks for crediting me.

**Comment by codefromthecrypt** [comment]
> @adriancole thank you. I didn't try to be pushy. Added a note for people to confirm themselves. This spec got a lot of support from many people in different forms. And it will be fair to give credits.

yep if I were listed as credit vs editor I would have felt
differently. I agree it is good to give credit

**Comment by plehegar** [comment]
Ack is the way to do this, and we only list names in general.

**Comment by nikmd23** [comment]
Thanks @SergeyKanzhelev, I've added a check on my name.

**Comment by SergeyKanzhelev** [comment]
@plehegar so just add a non-formative section called `Credits` in the end of the doc? I removed company names from the list.

**Comment by plehegar** [comment]
Here is an example:
 https://w3c.github.io/hr-time/#acknowledgments

**Comment by SergeyKanzhelev** [comment]
closing via #272
