### ISSUE TITLE
grammar in abstract

### ISSUE THREAD

**Issue by dret** [w3c/trace-context#285]
from the abstract:

> This specification defines standard headers and value format ...

this probably should say "value format*s*", right?

**Comment by SergeyKanzhelev** [comment]
it may also be value**s** format. I think it's a matter of taste. Please re-open if you feel strongly. I'm not a native speaker and happy to be wrong

**Comment by dret** [comment]
i don't think "This specification defines standard headers and values format" is grammatically correct.

**Comment by danielkhan** [comment]
Fixed with the last editorial review.
