### ISSUE TITLE
Clarify handling of multiple tracestate headers

### ISSUE THREAD

**Issue by arminru** [w3c/trace-context#289]
I see two problems arising from this statement:
https://github.com/w3c/trace-context/blob/5b8a2f357dffe517af6f879abfda38989eff315d/spec/20-http_header_format.md#L300-L303

---

#### Problem A: Reverse order of tracestate entries

RFC7230 (3.2.2. Field Order) defines:
> A recipient MAY combine multiple header fields with the same field
   name into one "field-name: field-value" pair, without changing the
   semantics of the message, by appending each subsequent field value to
   the combined field value in order, separated by a comma.

This would break the semantics of the tracestate field when a tracing system adds a tracestate header to the bottom (as it is usually done) and afterwards multiple tracestate headers are combined by appending them top to bottom according to the RFC. In this case, the most current entry would not end up being the left-most but the right-most entry in the resulting tracestate.

---

#### Problem B: Duplicate keys in multiple tracestate headers

Spec defines that only entry per vendor key is allowed:
https://github.com/w3c/trace-context/blob/5b8a2f357dffe517af6f879abfda38989eff315d/spec/20-http_header_format.md#L373-L374

I did not find a clear definition on how duplicate entries for the same key should be handled when they occur in different tracestate headers.
Example:
```
tracestate="vendor1:key1"
tracestate="vendor1:key2"
```
When the headers are processed or combined and duplicate keys occur, should:
1. the last entry (key2) be used, or
2. vendor1 be removed completely from tracestate, or
3. the entire tracestate be deemed invalid and be cleared, or
4. the entire trace be deemed invalid and be restarted

**Comment by yurishkuro** [comment]
> This would break the semantics of the tracestate field when a tracing system adds a tracestate header to the bottom (as it is usually done)

I don't follow. The following two header sets are equivalent per http specs:
```
# header set 1:
H: a, b, c

# header set 2:
H: a
H: b
H: c
```
(in other words, left-to-right in single header is equivalent to top-to-bottom in repeated headers).

Per Trace Context spec, the last tracer to update the `tracestate` is supposed to remove its own state from the list and add it as the first entry: "Modified keys MUST be **moved to the beginning of the list**". If it adds it as the last repeated header, it's not following the Trace Context spec:

https://github.com/w3c/trace-context/blob/5b8a2f357dffe517af6f879abfda38989eff315d/spec/20-http_header_format.md#L484-L486

Problem B - I agree, there could be clarification. The spec already says "Only one entry per key is allowed", so adding the same key twice is incorrect behavior. We could either adopt "max compatibility" stance and define the rule "only keep the first occurrence",  or adopt "max compliance" stance and discard the whole header or just the key. I would go with "only keep the first occurrence", on the assumption that the offending system still followed the rule from Problem A and put the new value at the front of the list, but failed to remove the old one.

**Comment by arminru** [comment]
A:
I see, so as long as the HTTP framework an implementation is using allows either choosing the position when adding a header (prepending on top rather than adding at bottom) or replacing the _first_ occurring header (with a correctly modified version) it should be fine.

B:
Sounds like a reasonable proposal, I'd also go with the latter 👍

**Comment by mwear** [comment]
@arminru I wanted to check in to see if your questions have been sufficiently answered or if you or the spec needs more clarification.

**Comment by mwear** [comment]
@arminru Let me know if you need anything further from this issue, otherwise I will close it out in a couple of days.

**Comment by arminru** [comment]
Thanks for checking back, Matthew! Please pardon my late response, I've been on vacation in September.
It is sufficiently answered, so closing is fine.
