### ISSUE TITLE
Clarify trace restarting scenarios

### ISSUE THREAD

**Issue by arminru** [w3c/trace-context#290]
https://github.com/w3c/trace-context/blob/5b8a2f357dffe517af6f879abfda38989eff315d/spec/20-http_header_format.md#L460-L469

This section is unclear to me. What is supposed to be a "secure network"? There is no definition given for that.
I suppose we are talking about crossing a "trust boundary" into our own domain/territory from public networks?
As this is not a MUST or SHOULD requirement, I would clearly state this as an example for when restarting a trace could make sense.

**Comment by danielkhan** [comment]
Closed with #300
