### ISSUE TITLE
Make downgrading the version an allowed mutation of traceparent

### ISSUE THREAD

**Issue by arminru** [w3c/trace-context#291]
**3.4 Mutating the traceparent field** defines a complete list of allowed mutations to traceparent:
- updating the parent ID
- updating the recorded flag and
- restarting the trace

Other mutations are prohibited:
https://github.com/w3c/trace-context/blob/5b8a2f357dffe517af6f879abfda38989eff315d/spec/20-http_header_format.md#L471-L472

**3.2.5 Versioning of traceparent**, however, states:
https://github.com/w3c/trace-context/blob/5b8a2f357dffe517af6f879abfda38989eff315d/spec/20-http_header_format.md#L274-L276

If I get the latter right, this is about mutating traceparent for an existing trace and *not* restarting it, correct?
If so, downgrading the version needs to be added to the list of allowed mutations.

**Comment by SergeyKanzhelev** [comment]
yes, this is an inconsistency

**Comment by danielkhan** [comment]
Fixed in #298
