### ISSUE TITLE
Always propagate entire trace ID

### ISSUE THREAD

**Issue by arminru** [w3c/trace-context#292]
The current spec allows trace IDs shorter than 16 bytes and only states that the full value *should* be propagated in any case:
https://github.com/w3c/trace-context/blob/5b8a2f357dffe517af6f879abfda38989eff315d/spec/20-http_header_format.md#L116-L119

I would define propagating the entire trace ID as a MUST requirement.

Note: This would be obsoleted by #262.

**Comment by AloisReitbauer** [comment]
Can this one be closed as the PR was merged

**Comment by arminru** [comment]
Yes, closing this since resolved in #297.
