### ISSUE TITLE
Add negative test cases for Tracestate value

### ISSUE THREAD

**Issue by reyang** [w3c/trace-context#304]
We need to have negative test cases which test against invalid tracestate value.

**Comment by reyang** [comment]
@markwolff

**Comment by SergeyKanzhelev** [comment]
can you please expand on what's needed. Perhaps examples of tests you think are missing

**Comment by reyang** [comment]
> can you please expand on what's needed. Perhaps examples of tests you think are missing

```
tracestate: foo=bar=baz
```
