### ISSUE TITLE
Anchor links across spec files don't work

### ISSUE THREAD

**Issue by iredelmeier** [w3c/trace-context#309]
Ideally, we should be able to create links within spec files that work both when the spec is rendered as regular Markdown (i.e., for viewing directly in GitHub) **or** on the W3C site. However, since the spec files are split in GitHub/Markdown form but consolidated on the W3C site, this doesn't really work right now.

One solution is to consolidate all the Markdown files, although this would mean we'd have a fairly giant file. What are the feelings about this? Anyone know if it would complicate the W3C rendering process?

**Comment by plehegar** [comment]
It won't complicate the W3C rendering process.
