### ISSUE TITLE
Typo in §2.3 Design overview (s/tracestate/traceparent/)

### ISSUE THREAD

**Issue by kqr** [w3c/trace-context#315]
The first bullet point in the section says

> `traceparent` describes the position of the incoming request in its trace graph in a portable, fixed-length format. Its design focuses on fast parsing. Every tracing tool MUST properly set `tracestate` even when it only relies on vendor-specific information in `tracestate`

but, given the surrounding text, it would make a lot more sense if the intended text of the bullet point was

> `traceparent` describes the position of the incoming request in its trace graph in a portable, fixed-length format. Its design focuses on fast parsing. Every tracing tool MUST properly set **`traceparent`** even when it only relies on vendor-specific information in `tracestate`

(Emphasis mine.)

Am I mistaken in my interpretation or is this a typo?

**Comment by mwear** [comment]
@kqr I believe you are correct about this being a typo.

**Comment by mwear** [comment]
Closing. This was resolved in #318. Thanks for opening this issue @kqr!
