### ISSUE TITLE
Verify tracestate key and value limits

### ISSUE THREAD

**Issue by mwear** [w3c/trace-context#324]
In the [3.3.1.3.1 Key](https://w3c.github.io/trace-context/#key) and [3.3.1.3.2 Value](https://w3c.github.io/trace-context/#value) sections we allow keys and values to be up to 256 characters in length. 

In [3.3.1.5 tracestate Limits](https://w3c.github.io/trace-context/#tracestate-limits) we recommend that tracing systems propagate at least 512 characters of a combined header, and that when the header is truncated, entries over 128 characters should be removed first.

If an implementor was to use the maximum sizes for their key and value, their trace state entry would be 513 characters long including the equals sign. It seems like having such generous limits on the key and value sizes could be setting up implementors for failure, or at least some frustration, as their entry would be both larger than the minimum amount of tracestate that should be propagated, and well over the suggested size that tracing systems should use when truncating.

Should we consider reevaluating these limits and make sure that we are absolutely happy with them for this version of the spec?

**Comment by mtwo** [comment]
Alternatively we could recommend that systems propagate at least the first _513_ characters of a combined header, which would allow at least once maximum size key value pair to be stored. Thoughts?

**Comment by mwear** [comment]
After thinking about this for a bit, I have come to a conclusion that I am happy with limits we have. It's true that the maximums are much higher than the recommended sizes, but they are maximums. Our recommendations should encourage most tracing systems to keep their entries below 128 bytes, but for tracing systems where this isn't possible, our maximums will still allow them to participate, albeit with a greater likelihood of being dropped as tracestate grows. 

Ultimately, there is no perfect size. The limits are arbitrary and whatever we choose may be too small or too large depending on the use case. Our current choices strike a reasonable balance and allow implementors to decide on the tradeoffs.

We can talk about this briefly if folks want to, or I can close the issue, but I really don't want to drag the group into a deep discussion about limits at this stage.

**Comment by mtwo** [comment]
Sounds good to me

________________________________

**Comment by mwear** [comment]
Closing as this is a non-issue.
