### ISSUE TITLE
Missing elements in the spec

### ISSUE THREAD

**Issue by jkowall** [w3c/trace-context#33]
Hello, I was just comparing this to what we do with our tracing in AppDynamics, and there are a few things that I believe a standard should have. I'll go from most concrete to most abstract. I am happy to write these up, however, is deemed to be most useful and most detailed.

- Support for other protocols. Offhand I see the need to support technologies which are not based on HTTP such as JMS, AMQP. Similarly, we may want to have a way to embed data into backend calls such as JDBC or ADO.NET. LDAP is another protocol we should add support into.  I'm happy to provide details in supporting these areas. 

- Adding in metrics or other data within the header and standard. For example, we embed additional business context or other data in the headers to enrich our agent decision making processes around data capture. These could be handled as baggage, but it would be good to have some of these metrics and business data be usable potentially. 

- Having the ability to pass a metric between two nodes, or have them be only shorter lived within the headers. 

- Headers to support thread correlation and async. We have a specific pattern for doing this, and it's typically a problem for any of the OSS tracing products I have seen. There are ways to do thread correlation which may be from a single transaction upstream, hence this is critical the way the header is designed and used.

Hope these ideas make sense, happy to discuss and contribute!

**Comment by yurishkuro** [comment]
@jkowall I think your point about multiple transport is spot on, that's a fairly high priority. If you're up to it, I would suggest you open separate issues for each of your items and provide more details, maybe describe what AppDynamics is doing for each and what your proposals are for this spec, so that people can see/understand how it is relevant/overlaps with their implementations.

**Comment by wu-sheng** [comment]
@jkowall Hi, welcome to join. I agree with @yurishkuro . AppDynamics have several very complex tracer, so happy to have you join us. If you can give me more details or sample data about your new headers would be great, and help we have enough context for that.

Other protocols are clearly enough. 

> I would suggest you open separate issues for each of your items and provide more details

+1.

**Comment by jkowall** [comment]
I will do that, thanks, @yurishkuro and @wu-sheng I have to be careful what I share, but we can work on the fundamentals. I will write them up.

**Comment by mtwo** [comment]
+1 with @yurishkuro and @wu-sheng, thanks @jkowall for the suggestions

Like Yuri, I think that having specifications for multiple transport types is this highest priority of these items. Like Jonah, I _suspect_ that passing metrics or other vendor-specific data is best served through baggage, unless we want these items to be included in the base spec - it'd be great to have a better understanding of AppDynamics' use cases here, as I'm admittedly somewhat naive.

@bogdandrutu FYI

**Comment by jkowall** [comment]
I'm concerned that "baggage" becomes a dumping ground for various stuff people want to do that's undefined. Instead, we should come up with a specific set of fields that allow interoperability. Baggage will become exactly that over time... meaning baggage :)

I'm creating some new issues for each of these today. I am happy to write them up.

**Comment by mtwo** [comment]
Sounds good!

**Comment by yurishkuro** [comment]
> I'm concerned that "baggage" becomes a dumping ground for various stuff people want to do that's undefined.

That is kind of the point of baggage, to allow pass-through context propagation without requiring intermediate nodes to understand what's in the context (http://pivottracing.io/).

**Comment by jkowall** [comment]
@yurishkuro my issue is that there is no construct making the data unusable across tooling. If everyone stuffs data there it becomes meaningless. The point of a standard would be to create structure.

**Comment by yurishkuro** [comment]
> If everyone stuffs data there it becomes meaningless.

You can say the same about HTTP headers in general, but clearly they are not useless. HTTP headers is just a transport mechanism for request-scoped metadata. You can standardize on some of them, but it does not make the actual general purpose mechanism useless. Baggage is the same - it's a general purpose transport mechanism for _transaction_-scoped metadata. We need to agree on the transport/protocol first, then we can start building applications on top of it. For a given application the baggage is not meaningless.

Here's an example of such application - targeted fault injection. The chaos monkey approach is great and all, but the search space of all possible faults for a complex system is too large to explore via random faults, so there are techniques for targeted fault injection where we decide for a certain transaction to inject faults into one or more places in the architecture. We can encode that scenario as a baggage item when we start a transaction, and have some layer in the architecture that executes fault injection instructions (e.g. in the service mesh). Nothing else in the architecture needs to understand what that baggage item means, they just _need to pass it along_.

This is not to say that there is no value in standardizing on _some_ baggage keys for certain widely used metadata, but the propagation format itself needs to be agnostic to the meaning of the baggage items to enable different applications that require transaction-scoped metadata.

**Comment by jkowall** [comment]
Anything which is key for monitoring and tracing should be well defined versus just using available fields to stuff things into them. This means that if an instrumentation is compliant you'll know exactly how it should look versus having to try to parse out implementation specific elements from a "junk drawer".

**Comment by SergeyKanzhelev** [comment]
@jkowall I see you opened separate issues for the individual topics in this one. I'm closing this one so every issue will be discussed separately. Please open more issues if I missed something in this discussion that is not captured in other threads.
