### ISSUE TITLE
Update tracestate test to validate new tenant format

### ISSUE THREAD

**Issue by toddwest** [w3c/trace-context#331]
There was an issue opened back in July that proposed a change to the format of the tenant id: https://github.com/w3c/trace-context/issues/316

That work eventually got merged via: https://github.com/w3c/trace-context/pull/322

However, the `key with vendor` format regex wasn't updated here: https://github.com/w3c/trace-context/blob/master/test/tracecontext/tracestate.py#L6

I think the change should be as simple as something like this:

```
_KEY_WITH_VENDOR_FORMAT = r'[a-z0-9][_0-9a-z\-\*\/]{0,240}@[a-z][_0-9a-z\-\*\/]{0,13}'
```

**Comment by reyang** [comment]
Both should be changed:
```python
_KEY_WITHOUT_VENDOR_FORMAT = r'[0-9a-z][_0-9a-z\-\*\/]{0,255}'
_KEY_WITH_VENDOR_FORMAT = r'[0-9a-z][_0-9a-z\-\*\/]{0,240}@[a-z][_0-9a-z\-\*\/]{0,13}'
```

**Comment by reyang** [comment]
@toddwest you're right, please refer to https://github.com/w3c/trace-context/pull/332#discussion_r326403795.

**Comment by toddwest** [comment]
Thank you for looking into it, @reyang!
