### ISSUE TITLE
Trace-Context W3C Candidate Recommendation 24 September 2019 Review Notes

### ISSUE THREAD

**Issue by bobstrecansky** [w3c/trace-context#334]
As promised in the meeting yesterday, I took notes on the current trace-context draft.  I've added the relevant portions of the document I had questions on below, with my comments on those particular pieces of the document immediately following.

```
3.2.2.3 trace-id
When a system operates with a trace-id that is shorter than 16 bytes, it SHOULD fill-in the extra bytes with random values rather than zeroes. Let's say the system works with an 8-byte trace-id like 3ce929d0e0e4736. Instead of setting trace-id value to 0000000000000003ce929d0e0e4736 it SHOULD generate a value like 4bf92f3577b34da6a3ce929d0e0e4736 where 4bf92f3577b34da6a is a random value or a function of time and host value.
```

Is there a reason that a unique time identifier isn’t part of the trace-id by default?  If a trace-id that is shorter than 16 bytes SHOULD fill in extra bytes with random values, couldn’t time be a key context here?  There may be reasoning behind this i’m not aware of.

```
3.2.2.3.2 trace-flags
The current version of this specification (00) only supports a single flag called sampled.
```

What are the plans for the trace-flags field in the future?  The spec mentions that the current version of the specification only supports a single flag called sampled.  What are some potential other future use cases for this field? 

```
3.2.2.3.3 Other Flags
The behavior of other flags, such as (00000100) is not defined and is reserved for future use. Vendors MUST set those to zero.
```

What is this reserved for?

```
3.2.4
Pass-through services should not analyze the version. They should expect that headers may have larger size limits in the future and only disallow prohibitively large headers.
```

What would be considered a `Prohibitively large header` in this context?

```
When the version prefix cannot be parsed (it's not 2 hex characters followed by a dash (-)), the implementation should restart the trace.
```

What happens if we get into a cyclical loop with this particular implementation?  A poor prefix is passed and cannot be parsed, the implementation restarts the trace, and the next prefix cannot be parsed?

```
3.3.1.1 tracestate Header Field Values
The tracestate field value is a list of list-members separated by commas (,). A list-member is a key/value pair separated by an equals sign (=). Spaces and horizontal tabs surrounding list-members are ignored. There can be a maximum of 32 list-members in a list.
```

What happens if there are more than 32 list-members passed?  Would some get dropped or would the trace become invalid?

``` 
3.3.1.2 list
Identifiers for a list are short (up to 256 characters) textual identifiers.
```

What should happen if list identifier becomes larger than 256 characters? Does it then become an invalid tracestate?  Would the next receiver of the trace make that determination?

```
3.3.1.3.1 Key
Note: Identifiers MUST begin with a lowercase letter or a digit, and can only contain lowercase letters (a-z), digits (0-9), underscores (_), dashes (-), asterisks (*), and forward slashes (/).
```

Should the @ sign be included in this Note?  What happens if the identifier includes something other than these characters?

```
3.3.1.5 tracestate Limits:
Vendors SHOULD propagate at least 512 characters of a combined header. This length includes commas required to separate list items and optional white space (OWS) characters.
```

Is there ever an upper bound for this value?

```
3.4 Mutating the traceparent Field
Restart trace: All properties (trace-id, parent-id, trace-flags) are regenerated. This mutation is used in services that are defined as a front gate into secure networks and eliminates a potential denial-of-service attack surface. Vendors SHOULD clean up tracestate collection on traceparent restart. There are rare cases when the original tracestate entries must be preserved after a restart. This typically happens when the trace-id is reverted back at some point of the trace flow, for instance, when it leaves the secure network. However, it SHOULD be an explicit decision, and not the default behavior.
```

Could it be possible to have some sort of identifier in the traceparent or the tracestate if a trace has been restarted?  I could see that as being beneficial in the future if you’re trying to understand the current state of a trace.

```
Downgrade the version: This version of the specification (00) defines the behavior for a vendor that receives a traceparent header of a higher version. In this case, the first mutation is to downgrade the version of the header. Other mutations are allowed in combination with this one.
```

I believe initially there won’t be anything to downgrade to?

```
6. Privacy Considerations
Requirements to propagate headers to downstream services, as well as storing values of these headers, open up potential privacy concerns. Tracing vendors MUST NOT use traceparent and tracestate fields for any personally identifiable or otherwise sensitive information. The only purpose of these fields is to enable trace correlation.
```

Who owns validating that the traceparent and tracestate fields don’t contain PII?  Is that the responsibility of the receiver of the trace?  I’d assume not, because that would be a difficult problem to solve.  It appears this is dicussed more in (7), but it may be purposefully ambiguous?

**Comment by bobstrecansky** [comment]
@danielkhan mentioned he is planning on reviewing this.

**Comment by codefromthecrypt** [comment]
> 3.2.2.3 trace-id
When a system operates with a trace-id that is shorter than 16 bytes, it SHOULD fill-in the extra bytes with random values rather than zeroes. Let's say the system works with an 8-byte trace-id like 3ce929d0e0e4736. Instead of setting trace-id value to 0000000000000003ce929d0e0e4736 it SHOULD generate a value like 4bf92f3577b34da6a3ce929d0e0e4736 where 4bf92f3577b34da6a is a random value or a function of time and host value.

This is a really bad idea as it will directly interfere with known practice and break traces that wouldn't break before. For example, if one node downgrades to 64-bit, making 2 outgoing calls, then they propagate random data.. it will appear now as 3 different traces.

**Comment by codefromthecrypt** [comment]
here's a thread about the zeros thing https://github.com/jaegertracing/jaeger-client-java/pull/649#discussion_r316931551

**Comment by codefromthecrypt** [comment]
In the jaeger thread, there was an interpretation that "When a system operates with a trace-id that is shorter than 16 bytes" it means only when it is provisioning (generating) a trace ID. I think it is dangerous to make that assumption.

It is commonplace for components to inherit (operate with) IDs provisioned or generated upstream. For example, it is commonly the case that proxies provision trace IDs, and sometimes nodes downstream can't push 128bit IDs, so they downgrade.

If the intent was in fact to say that the backfilling random was about generating, it is entirely unintuitive. If you can generate random 64 bit ID and also backfill 64 more bits of random characters, you can generate 128 bit ID! I don't believe many people would think that the associated paragraph is about generating IDs.

My strong recommendation is to be clear about what you are discussing. 3.2.2.3 looks almost obviously a discussion of how to work/operate in mixed environments, and makes a troubling recommendation. Either re-word this to say it is about ID provisioning, or please remove the bad advice about back filling randomly.

**Comment by danielkhan** [comment]
@adriancole Would it be possible to raise a separate issue or a PR on that so that we can discuss it in a controlled way?

**Comment by codefromthecrypt** [comment]
@danielkhan sure.. https://github.com/w3c/trace-context/issues/337

aside: If separate issues are preferred (which I'd agree with), probably an issue like this isn't a good practice then, as it is a cobbling of a dozen questions before I noticed/piped in. Maybe in general use a wiki or something else for notes until someone digests them into issues.

**Comment by danielkhan** [comment]
> ```
> 3.2.2.3 trace-id
> When a system operates with a trace-id that is shorter than 16 bytes [...]
> ```
> Is there a reason that a unique time identifier isn’t part of the trace-id by default? If a trace-id that is shorter than 16 bytes SHOULD fill in extra bytes with random values, couldn’t time be a key context here? There may be reasoning behind this i’m not aware of.

`trace-id` should not have any built-in semantic that implementors build upon and rely on.
Especially in distributed systems and cross-vendor scenarios, time is pretty relative and tracing systems have their own way to represent time in a consistent way.

> ```
> 3.2.2.3.2 trace-flags
> The current version of this specification (00) only supports a single flag called sampled.
> ```
> What are the plans for the trace-flags field in the future? The spec mentions that the current version of the specification only supports a single flag called sampled. What are some potential other future use cases for this field?

There may be use cases tomorrow that we can not anticipate today.
This is purely for the spec to be future proof.

> ```
> 3.2.2.3.3 Other Flags
> The behavior of other flags, such as (00000100) is not defined and is reserved for future use. [...]
> ```
> What is this reserved for?

As with `3.2.2.3.2` this is just a way to allow needed additions we don't know today in upcoming versions.

> ```
> 3.2.4
> [...] They should expect that headers may have larger size limits in the future and only disallow prohibitively large headers.
> ```
> What would be considered a `Prohibitively large header` in this context?

This is up to the implementor of the pass-through system. A `Prohibitively large header` can be anything that might indicate a DOS attack or abuse of the header.
 
> ```
> When the version prefix cannot be parsed [...]
> ```
> What happens if we get into a cyclical loop with this particular implementation? A poor prefix is passed and cannot be parsed, the implementation restarts the trace, and the next prefix cannot be parsed?

There is nothing like a 'poor' prefix. It's either correct or not.
So your scenario would imply that either the function setting the prefix or the function checking the prefix is not following the spec.

> ```
> 3.3.1.1 tracestate Header Field Values
> The tracestate field value is a list of list-members separated by commas (,) [...]
> ```
> 
> What happens if there are more than 32 list-members passed? Would some get dropped or would the trace become invalid?

Yes - dropping is am allowed mutation: https://www.w3.org/TR/trace-context/#mutating-the-tracestate-field

But - we may want to add that to the limits section as the 32 entry limit is mentioned here and just here and actually imposes a limit. WDYT @SergeyKanzhelev ?

> ```
> 3.3.1.2 list
> Identifiers for a list are short (up to 256 characters) textual identifiers.
> ```
> What should happen if list identifier becomes larger than 256 characters? Does it then become an invalid tracestate? Would the next receiver of the trace make that determination?

Yes - https://www.w3.org/TR/trace-context/#a-traceparent-is-received. Point 3.

> ```
> 3.3.1.3.1 Key
> Note: Identifiers MUST begin with a lowercase letter or a digit, and can only contain lowercase letters (a-z), digits (0-9), underscores (_), dashes (-), asterisks (*), and forward slashes (/).
> ```
> Should the @ sign be included in this Note? What happens if the identifier includes something other than these characters?

This is in the next paragraph: https://www.w3.org/TR/trace-context/#key
'For multi-tenant vendor scenarios'.

> ```
> 3.3.1.5 tracestate Limits:
> Vendors SHOULD propagate at least 512 characters of a combined header. This length includes commas required to separate list items and optional white space (OWS) characters.
> ```
> Is there ever an upper bound for this value?

No there isn't. You can have a 768 length header within your own system and still be compliant with the spec but if that header crosses boundaries you have to expect that it may get truncated to <=512.

> ```
> 3.4 Mutating the traceparent Field
> Restart trace: All properties (trace-id, parent-id, trace-flags) are regenerated. [...]
> ```
> Could it be possible to have some sort of identifier in the traceparent or the tracestate if a trace has been restarted? I could see that as being beneficial in the future if you’re trying to understand the current state of a trace.

Right now, this is up to the monitoring system to track. It might be a future addition if we find valid use cases.

> ```
> Downgrade the version: This version of the specification (00) defines the behavior for a vendor that receives a traceparent header of a higher version. In this case, the first mutation is to downgrade the version of the header. Other mutations are allowed in combination with this one.
> ```
> I believe initially there won’t be anything to downgrade to?

This covers the case when there is a new version of the spec but implementations only know the old one so far. The implementation needs to have a way to handle such cases gracefully.

> ```
> 6. Privacy Considerations
> Requirements to propagate headers to downstream services [...]
> ```
> 
> Who owns validating that the traceparent and tracestate fields don’t contain PII? [...]

This can not be validated but vendors MUST make sure that they don't put privacy/security-critical information on the headers. If they do, they don't comply with the spec.
