### ISSUE TITLE
How multiple APMs in a process can "collaborate" on a given trace-context?

### ISSUE THREAD

**Issue by yurishkuro** [w3c/trace-context#335]
@untitaker [brought up](https://gitter.im/open-telemetry/community?at=5d8ba83e34a7236bf5bcdd49) this use case where a single service is instrumented with more than one APM, who would interfere with each other trying to deal with trace-context headers.

**Comment by untitaker** [comment]
Any behavior for collaboration I can think of is to either allow multiple traceparents (has a bunch of implications that probably nobody wants to think of) or to make implementors keep their existing proprietary headers (not great but I believe the best idea if the spec wants to solve this).

I believe this usecase is not too popular. It might be fine not to do anything as part of the spec. But I do not want to end up in a state where all APMs are in direct conflict with each other, so my hope is that they still do something beyond this spec to make sure this doesn't happen.

**Comment by danielkhan** [comment]
Currently, we see no way of mitigating this on a spec level. 
Having multiple tracing systems in one process is always cumbersome.
Depending on the platform and the participating vendors an APM system needs to apply heuristics to detect other vendors and handle this case.
One possible way would be to make sure to not override existing headers on outbound requests and use them instead. There may be other options that we should explore.

**Comment by untitaker** [comment]
>One possible way would be to make sure to not override existing headers on outbound requests and use them instead.

I think this is impossible to correctly implement as it would mean that at any point in the trace when the trace header is being sent out, vendor A may see an existing header from vendor B with a separate trace id. Does that mean vendor A should just drop its own trace ID? Even if vendor A manages to rewrite all their spans such that there's just one trace ID, there is still the question what to do with parent IDs, as dropping one parent ID basically means that one entire tree of spans is trunchated at its leaves.
