### ISSUE TITLE
test fails on empty tracestate value

### ISSUE THREAD

**Issue by toumorokoshi** [w3c/trace-context#340]
The trace-context test cases currently have a test that considers an empty value as illegal:

https://github.com/w3c/trace-context/blob/master/test/test.py#L797.
However, the EBNF grammar for value currently says that value can be any number of nblk-chrs from 0 to 255, implying the empty string is allowed:

https://github.com/w3c/trace-context/blob/master/spec/20-http_header_format.md#value

It seems like either the spec or test should be changed.

**Comment by reyang** [comment]
The spec enforces the value to have at least one nblk-chr at the end of the value.

```value    = 0*255(chr) nblk-chr```
