### ISSUE TITLE
Warning message against implementation

### ISSUE THREAD

**Issue by ocelotl** [w3c/trace-context#345]
Hello

This is just a question, apologies in advance if this is not the right way to ask.

https://w3c.github.io/trace-context/ is currently displaying a warning message that says:

**This is a preview
Do not attempt to implement this version of the specification. Do not reference this version as authoritative in any way. Instead, see https://w3c.github.io/trace-context/ for the Editor's draft.**

I am confused since the link in the warning message points to the same page that is displaying the warning message.

Thank you!

**Comment by SergeyKanzhelev** [comment]
Just to unblock you - this is an authoritative source: https://www.w3.org/TR/trace-context/

We need to fix some metadata. @plehegar can you suggest what may be wrong with it?

**Comment by SergeyKanzhelev** [comment]
May it be because of this line? https://github.com/w3c/trace-context/blob/f37a97317af5cae528d099c874c8007351e847b5/index.html#L53
