### ISSUE TITLE
Clarify "opaque"

### ISSUE THREAD

**Issue by ocelotl** [w3c/trace-context#348]
The term *opaque* is used several times in the specification:

https://www.w3.org/TR/2019/CR-trace-context-20190813/#relationship-between-the-headers
https://www.w3.org/TR/2019/CR-trace-context-20190813/#tracestate-header-field-values
https://www.w3.org/TR/2019/CR-trace-context-20190813/#value
https://www.w3.org/TR/2019/CR-trace-context-20190813/#privacy-of-tracestate-field

Nevertheless, the meaning of this term in these situations may not be very easy to understand to readers that are less familiar with the document. A explanation would be very useful.

**Comment by SergeyKanzhelev** [comment]
Opaque means that for tracing system that doesn’t know about this key - it is just a blob of bytes

We need to find a way to clarify it in a spec. I forgot that this word confused me when I first seen it and by now it feels very natural =)

**Comment by danielkhan** [comment]
At the first occurence we should explain what it is. I'll take that one.
