### ISSUE TITLE
Correlation Context Should be Split

### ISSUE THREAD

**Issue by jkowall** [w3c/trace-context#36]
Having a single header for all of this data will be detrimental for several reasons. The first being that metrics are numbers, and we can do maths on them. We'll likely have systems which want these metrics for context. They can be sniffed or captured at various levels. Similarly, there are many use cases for Metadata, it could be the context of a transaction for other tools (security, forensics, topological systems), or instructions for orchestration. There are various reasons these should be split.

Metrics - measurename=number , processingtime=34.534
Metadata - metadataname=metadata , browserlocation=Boston,MA

**Comment by yurishkuro** [comment]
I am not sure what you're proposing. The type of value (string or number) encoded in a name/value pair in the correlation context does not require splitting the header, ultimately all values are strings in the HTTP representation.

**Comment by jkowall** [comment]
I just think we should have types for this data to make it easier to consume the data in various ways generically. By mixing data types it limits what can be done.

**Comment by yurishkuro** [comment]
The current spec has a placeholder for "properties", if you look at the prior PR the original proposal contained the value types, like 

```
Correlation-Context: someKey=someValue;type=int, someKey2=false;type=bool
```

It didn't make it to the final spec. I think one argument is - if your application doesn't care about a given key, you don't care what type it is either, just pass it along. If you do care, then you should already know what type of value you're expecting, so you can parse it accordingly.

**Comment by jkowall** [comment]
@yurishkuro thanks for the feedback, it makes sense to me. The reason I thought this would be useful would be for reasons like this:

Instrumentor uses different fields. Packet analysis or host-based analysis already knows which data should be used for what purpose. Remember that some systems (Prometheus for example) would like metrics only, while other systems (ELK for example) would probably be more interested in metadata or events. 

I'm thinking of interoperability here, not that we can't just combine both types of data into a single header.

**Comment by SergeyKanzhelev** [comment]
I think single header will be better just for the ease of maintenance. Please up vote this issue if you need type information: https://github.com/TraceContext/tracecontext-spec/issues/22

**Comment by SergeyKanzhelev** [comment]
Moved to Correlation-Context repository
