### ISSUE TITLE
ABNF improvement

### ISSUE THREAD

**Issue by plehegar** [w3c/trace-context#364]
From [Ietf-message-headers](https://mailarchive.ietf.org/arch/msg/ietf-message-headers/UqZZ_IRZ4Dvvc8_KEyRkkkHWkSU):
[[

The ABNF currently says:

> list  = list-member 0*31( OWS "," OWS list-member )
> list-member = key "=" value
> list-member = OWS

That's invalid, you can't define "list-member" twice; make it:

list  = list-member 0*31( OWS "," OWS list-member )
list-member = (key "=" value) / OWS

or simpler:

list  = #31 list-member
list-member = key "=" value

There's also a problem that the ABNF does not allow whitespace around
"=", but the prose does.
]]

(following up from #120)

**Comment by danielkhan** [comment]
I'll add =/ to denote the OR

**Comment by plehegar** [comment]
To be clear: whitespaces around '=' are disallowed? ie 
congo=congosFirstPosition,rojo =rojosFirstPosition,congo =congosSecondPosition
is invalid.
Correct?

**Comment by danielkhan** [comment]
I'm in favor of not allowing this.
There should not be a reason for a system to add trailing whitespace to a key.
Where in the prose do we state that we allow whitespace around `=`?

@SergeyKanzhelev - please weigh in as you did the change to the ABNF.

**Comment by dyladan** [comment]
Created #461 to track backporting the invalid ABNF fix part of this to level-1

The whitespace question is separate and will need its own separate issue which we will have to decide if it is an erratum separately.

**Comment by dyladan** [comment]
@plehegar can you point out to me where the prose allows OWS around the `=`? I can't seem to find it in the level-1 spec.

**Comment by plehegar** [comment]
I wasn't able to find the prose in the published level 1 spec nor in the main branch.

**Comment by kalyanaj** [comment]
@dyladan Have all the issues described here been already covered as part of your PRs related to this? If so, can this be closed, or do we need to still track any open issues here?
