### ISSUE TITLE
Response header name

### ISSUE THREAD

**Issue by dyladan** [w3c/trace-context#371]
In the current response header PR #365 the name `tracemeta` is used. @mtwo brought up that a better name might be `traceresponse` which I quite like https://github.com/w3c/trace-context/pull/365#discussion_r358968766. This issue is to gather feedback on this idea.

**Comment by nicmunroe** [comment]
I don't have a strong preference on the name. `tracemeta` seems overly broad. `traceresponse` seems better to me, but maybe not perfect either. What about `traceresult`?

I feel like the perfect name exists somewhere, but I can't quite come up with it. 🤷‍♂

**Comment by dyladan** [comment]
I originally went with `tracemeta` to illustrate that it was describing an existing trace (which was created with `traceparent`) and not creating a new one. `traceresponse` seems like a fair idea from that standpoint and I agree that the word `meta` is pretty broad (not to mention overloaded in a lot of contexts). The other idea I had considered was `traceresult` actually, as it describes the result of the `traceparent` behavior (e.g. was it sampled? was the trace-id changed? etc).

summary of possible options:

- tracemeta - overly broad?
- traceresponse
- traceresult

**Comment by yurishkuro** [comment]
+1 traceresponse

**Comment by nicmunroe** [comment]
> The other idea I had considered was traceresult actually, as it describes the result of the traceparent behavior (e.g. was it sampled? was the trace-id changed? etc).

This is why I'm learning towards traceresult out of the 3 listed options. My second choice would be traceresponse.

**Comment by dyladan** [comment]
Tentatively going with traceresponse for now. can revisit later if needed
