### ISSUE TITLE
Clarify the requirements of short `trace-id` in section 8.4

### ISSUE THREAD

**Issue by justinfoote** [w3c/trace-context#379]
Several of our engineers have been tripped up by the language in [section 8.4](https://w3c.github.io/trace-context/#interoperating-with-existing-systems-which-use-shorter-identifiers) -- they've interpreted it to mean that they should accept a traceparent with a short traceId, like this:
```
00-24160746bbaecabc-393951cc1a8d5e9e-00
```

There is a test asserting that implementations restart the trace if such a traceparent header is received: https://github.com/w3c/trace-context/blob/master/test/test.py#L303

I'd like us to clarify that the non-normative section 8.4 only applies to accepting short traceIds from legacy non-compliant tracers in a non-w3c payload format, and that it doesn't change the normative traceparent requirements in section 3.2.

**Comment by dyladan** [comment]
So this is for accepting, for example, the jaeger request format which has a shorter trace ID, and propagating it using trace context?

**Comment by justinfoote** [comment]
@dyladan that is my understanding, yes.

**Comment by dyladan** [comment]
Actually it looks to me like this is the opposite based on current wording. It is what a system that cannot process a 32 character trace id should do when it receives a full trace id. Maybe guidelines should be added for the opposite situation like the one I described also.

**Comment by justinfoote** [comment]
Interesting.  I hadn't read it that way, but I can see how this section might have been intended for that.  
This text:
> For better interoperability between a fully compliant systems with these existing systems, the following practices are recommended:

Doesn't make things totally clear though.  These practices are recommended to whom?  To a compliant system trying to interop, or to a non-compliant system trying to appear as compliant as possible?

**Comment by dyladan** [comment]
I mean you can't make recommendations to a non-compliant system. If that system can change it should just become compliant.

**Comment by SergeyKanzhelev** [comment]
@justinfoote it was never the intent to accept shorter ID. The section is suggesting that if you can only operate with 16 bytes - you need to prepend it with zeroes.

**Comment by justinfoote** [comment]
OK.  I'm feeling like my changes haven't actually increased clarity, and perhaps the existing text is clear enough.  I'll close this issue and the related PR.
