### ISSUE TITLE
Should span annotations be supported?

### ISSUE THREAD

**Issue by deafgoat** [w3c/trace-context#385]
See `Annotations` at https://godoc.org/go.opencensus.io/trace#SpanData for more.

This is a pretty useful part of span data but I couldn't find any reference to it in the spec at https://w3c.github.io/trace-context/

**Comment by SergeyKanzhelev** [comment]
Trace Context defines the format of `SpanContext` propagation over the wire. How would annotations fit into this specification? I see how `MessageEvents` may be related with the individual message-id, but even this is not covered in this specification. Please re-open if you have any question.

**Comment by deafgoat** [comment]
Thanks for all your work on this and the quick response @SergeyKanzhelev.

I'm not an expert on the specification but was mostly wondering about why certain functionality (which several DT applications support) - e.g. `Annotations`, or even `MessageEvents` - aren't covered in the specification.

**Comment by SergeyKanzhelev** [comment]
There are many parts of Distributed Tracing that will benefit from standardization. This specification covers the propagation part of it - what exactly will be sent over the wire so anybody can stitch calls together. Other aspects like how to represent telemetry item describing the incoming request or outgoing call may be covered in future in separate specs.

```
| A |  --------------->  | B |
        trace context
```
