### ISSUE TITLE
Bogus trace and parent IDs when not sampling  

### ISSUE THREAD

**Issue by basti1302** [w3c/trace-context#390]
### Problem

I recently [implemented this specification](https://github.com/instana/nodejs-sensor/pull/204) for [Instana's Node.js tracer](https://github.com/instana/nodejs-sensor) and while doing so, came across a situation that might have room for improvement:

- A process instrumented by a tracing tool receives an HTTP request without the `traceparent` and `tracestate` header. 
- The tracing tool decides to _not_ record trace data.
- The instrumented process makes outgoing HTTP requests in the context of the initial incoming request.

Since there are not trace context headers in the incoming request, we can assume that this is the first process in line that is instrumented by a tracing tool, that is, the request is coming from a non-instrumented client. 

**What is the tracing tool supposed to do in this situation?**

According to [§3.2.2.5.1](https://www.w3.org/TR/trace-context/#sampled-flag), the decision to not record trace data SHOULD be communicated downstream:

> If a component made definitive recording decision - this decision SHOULD be reflected in the sampled flag.

This also implies that the tracing tool SHOULD send the `traceparent` header on outgoing requests, as there are not other means of communicating the recording decision downstream.

For a valid `traceparent` header, the tracing tool needs to set the `trace-id` and `parent-id` fields of that header. If it had received a `traceparent` header, it would simply use the IDs from that incoming header, but since the initial request did not have that header, this is not possible.

From my point of view, a compliant tracing tool can only choose between two options:
1. Create new bogus trace-id and parent-id values and send those downstream, together with the trace flags value `00`.
1. Do not set a `traceparent` header at all on outgoing requests.

The first option is quite ugly, as there now is a trace-id and a parent-id floating around that are not associated with any actual trace and span that is present in any of the participating APM systems. 
 
The second options is also not optimal because it does not allow to pass down the recording decision. It is also in conflict with the (non-normative) section [§4.2 No traceparent Received](https://www.w3.org/TR/trace-context/#no-traceparent-received), which says:

> the vendor creates a new trace-id and parent-id that represents the current request. [...]
> The vendor sets the traceparent and tracestate header for the outgoing request.

I would like to discuss/ask:

- whether this understanding of the spec is correct and shared by others (or if I have missed something),
- what other existing implementations are doing in this particular situation.

#### Do Not Send `traceparent`/`tracestate`

The spec could mandate explicitly to not send `traceparent` and `tracestate` at all in this particular situation. 

In its current form, the spec neither says that a tracing tool must always set these headers (although section 4.2 implies that IMO) nor that a tracing tool can choose to not set these headers in particular situations.

#### Allow Void IDs

The spec could allow a tracing tool to send down a trace-id and parent-id that signals that there is no actual trace/parent span associated with these IDs. For example, a tracing tool could set `00-00000000000000000000000000000000-0000000000000000-00` in this situation. Those all-zero IDs are considered invalid in the current form of the spec, so there is no ambiguity between these IDs and actual IDs associated with existing traces/spans.

However, there are probably backward compatibility concerns here. When tracers start to send down all-zero IDs, downstream tracers might
- interprete these as invalid and restart the trace (which would be acceptable in this situation, no trace data has been recorded yet), or
- they might not have implemented a specific check for all zero IDs and keep using that ID _and_ record trace data with trace-id `0000...`.

**Comment by yurishkuro** [comment]
In the Jaeger SDKs, the new trace ID is always generated in the situation you described, and duly propagated downstream, with the sampling flag 0. Even though the tracing infrastructure is not collecting data for this request, the unique trace ID is still useful and used by other systems, e.g. logs are being tagged with it and can be correlated across services. Unique span IDs are also generated at every hop.

**Comment by danielkhan** [comment]
Using a random ID is considered to be best-practice. As @yurishkuro mentioned, it can be still used in logs. We should revisit this topic to make it more explicit in level-2.

**Comment by basti1302** [comment]
I added #433 to make this aspect a bit more explicit.
