### ISSUE TITLE
Define purpose of correlation context

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#41]
Currently the definition and example of what correlation context is about are misleading. We should define that this is for tracing tool usage only. We should adjust the examples to reflect vendor specific extension like hierarchic correlation.

Happy to take the first run at this one.

**Comment by wu-sheng** [comment]
> Currently the definition and example of what correlation context is about are misleading.

Mislead to where? I am a little confused. This whole repository is about tracing context propagation. You can see that in our goal: https://github.com/TraceContext/tracecontext-spec#goal

**Comment by codefromthecrypt** [comment]
>
> Mislead to where? I am a little confused. This whole repository is about
> tracing context propagation. You can see that in our goal:
> https://github.com/TraceContext/tracecontext-spec#goal
>
> Hi, Sheng. I will export a copy of the workshop notes to you in PDF. Main
thing is that the correlation-context is not adoptable by a number of
parties due to it being unbounded and other reasons. One way we discussed
to make trace-context in general adoptable by major players is
re-associating the correlation-context to essentially the carrier of
extended *required* data about the trace context. For example, this can
hold extra fields needed by the originator of the trace. This is different
than its former scope which was arbitrary data.

https://docs.google.com/document/d/1uZpf7-X1cojSMhghYGP4O5DVVHtISrDq-HlwBKaDjDg/edit

**Comment by AloisReitbauer** [comment]
I was referring to the correlation context. We should not have an example with username etc. in there. Makes sense?

**Comment by yurishkuro** [comment]
maybe it should not be called a general purpose `Correlation-Context` then, but mention tracing, e.g. `Trace-Correlation`

**Comment by SergeyKanzhelev** [comment]
I agree with @yurishkuro - `correlation-context` better suites the baggage. Maybe `Trace-Context-Externded` or `Trace-Context-All`? 

Alternatively use `Trace-Context` for name/value pairs and `Trace-Id` for "essential" fields extracted for performance.

Any suggestions on thread?

CC: @bogdandrutu explicitly

**Comment by codefromthecrypt** [comment]
what? someone dared to suggest a naming convention?! :) I like
trace-context-ext (eventhough it stutters)

**Comment by bogdandrutu** [comment]
👍  "trace-context-ext"

**Comment by wu-sheng** [comment]
`trace-context-ext` is good for me.

**Comment by SergeyKanzhelev** [comment]
Is PR looks ok?

**Comment by wu-sheng** [comment]
@SergeyKanzhelev `Correlation Context HTTP Header Format` stays only for `baggage`, am I right?

**Comment by SergeyKanzhelev** [comment]
Yes, that's the idea

**Comment by wu-sheng** [comment]
@SergeyKanzhelev Review is done. Just a suggestion.

**Comment by SergeyKanzhelev** [comment]
@AloisReitbauer I know the baggage may not be used by DynaTrace. However there are many libraries that propagate tags or baggage defined by user. I think we captured the purpose of `C-C`. So I'm closing the issue. Please re-open if it needs extra clarification
