### ISSUE TITLE
What's the recommended guideline for generating parent-id?

### ISSUE THREAD

**Issue by prakashjmsft** [w3c/trace-context#412]
From here - https://www.w3.org/TR/trace-context/#parent-id

_This is the ID of this request as known by the caller (in some tracing systems, this is known as the span-id, where a span is the execution of a client request). It is represented as an 8-byte array, for example, 00f067aa0ba902b7. All bytes as zero (0000000000000000) is considered an invalid value._

_Vendors MUST ignore the traceparent when the parent-id is invalid (for example, if it contains non-lowercase hex characters)._

Current guidelines for parent-id mentions this should be an 8-byte array. But, we are missing guidelines/recommendations that this should be locally unique within the context of a trace? Also, how have SDKs implemented this to ensure span-id is unique within the context of a trace? We need to elaborate the guidelines similar to trace-id - https://www.w3.org/TR/trace-context/#considerations-for-trace-id-field-generation

**Comment by dyladan** [comment]
Looks like https://www.w3.org/TR/trace-context/#privacy-of-traceparent-field is the only place where it is even mentioned.

>The traceparent field is comprised of randomly-generated numbers.

We should probably add some wording for v2.

**Comment by justinfoote** [comment]
Agreed.  
In fact, I think sections 8.1 and 8.2 could both apply as-written to parent-id as well as trace-id.  

Section 8 is non-normative.  Do we need to wait until version 2 to add guidelines?

**Comment by yurishkuro** [comment]
I am not in favor of being strict about HOW the IDs are generated, it's enough to describe what expectations they should satisfy, like "best-effort to be unique within the trace" for span id.

**Comment by justinfoote** [comment]
OK, I can see this argument, and I like where you're going with the wording.  

Still, can we add a non-normative parent id guideline without waiting until V2?  Do we want to?

**Comment by dyladan** [comment]
As discussed at the previous meeting, I will create a PR which adds non-normative wording suggesting trace ids should be unique, and that span ids should be unique within the trace. Randomness will not be required, but I may suggest it as a simple approach.
