### ISSUE TITLE
Contradiction in TraceState requirements

### ISSUE THREAD

**Issue by dyladan** [w3c/trace-context#422]
It is confusing that an updated key MUST be moved to the left, but a newly added key only SHOULD be added on the left. If you delete your key, then add your key somewhere other than the start of the list (because that requirement is only SHOULD), haven't you edited the key without moving it left? I think this is a contradiction in the spec.

_Originally posted by @dyladan in https://github.com/w3c/trace-context/pull/421#r482283902_

**Comment by mtwo** [comment]
We can loosen the requirements to state 'SHOULD' in both cases. This would preserve the intent and not be a breaking change.

**Comment by dyladan** [comment]
Will that go into the "current" version or have to wait for v2? If v2, I would argue making the change to MUST in both cases (assuming we are allowed to make breaking changes for v2?).

**Comment by dyladan** [comment]
@danielkhan @SergeyKanzhelev @mtwo I was going to make this change, but as we discussed at the meeting Tuesday, we wanted the change to apply to v1. Am I correct that I should branch from and create a pull request into [`level-1` branch](https://github.com/w3c/trace-context/tree/level-1)?

**Comment by dyladan** [comment]
I created a PR. Once it is merged we can backport to level 1
