### ISSUE TITLE
Encourage traceresponse to be provided even when traceparent is used

### ISSUE THREAD

**Issue by briancr-ms** [w3c/trace-context#437]
The current proposal for traceresponse says, "The trace-id field is an optional part of the traceresponse response header. If the request header contains a valid traceparent with a trace-id, and the callee does not use a different trace-id, the callee SHOULD omit the trace-id field from the traceresponse." The proposal includes similar language for proposed-parent-id.

In order to enable consistent troubleshooting, if a response includes traceresponse, we would like it to always contain the trace-id and proposed-parent-id, even if a traceparent was provided on the request.

One use case that drives this request is a customer support use case: we want to give instructions to customers to always provide the traceresponse as part of our troubleshooting process. If the traceresponse is not emitted when a traceparent with a trace-id is provided, getting the right diagnostic information from customers becomes more complex and error prone.

**Comment by SergeyKanzhelev** [comment]
Hi Brian! Nice to see you here.

CC @Kanwaldeep who you can sync up internally if needed.

We are currently running the workshop and this is exactly what was discussed among other changes. Tune in for the upcoming changes. Support was named the number one priority scenario.

**Comment by briancr-ms** [comment]
Hi Sergey--it's nice to see you here, too!

Thanks for pointing me to Kanwaldeep--Kanwaldeep suggested that I create an issue so that this input can be seen by the group, so we've been discussing internally.

It's great to hear that there will be some changes to address the support use case. I look forward to seeing those updates when they're ready.

**Comment by dyladan** [comment]
@briancr-ms to sum up what we discussed, the response header will be receiving drastic changes. We are going to attempt to move forward with a format very similar to the request header with no optional fields, and remove the idea of the "proposed parent" field, which will be replaced with the span id used by the receiver. For your support case, this will mean the trace id, span id, and traceflags will be always included in the response header.

In terms of always returning the response header, I had not considered the issue you bring up. It would indeed be annoying to have to explain to customers that the trace id is only sometimes returned and in what specific cases. Keep in mind that the recommendation you are referring to is non-normative, and you always have the option to return the header with all fields if you want. That said, I'll consider changing the wording to reflect that it may be useful to always return the header for support use cases.

**Comment by dyladan** [comment]
@briancr-ms do the changes in #443 satisfy you? I would appreciate a review on that PR if you have time.

**Comment by briancr-ms** [comment]
Thanks. I took a look at the PR and these changes look good. I approved the PR.
