### ISSUE TITLE
How should tracestate list members be truncated when they exceed 32?

### ISSUE THREAD

**Issue by MrAlias** [w3c/trace-context#440]
The tracestate header field is specified to contain at most 32 list-members. What is the expected behavior when another list-member is added?

Should [the truncation schema](https://www.w3.org/TR/trace-context-1/#tracestate-limits) be used to make room for the new member or is that just the action that needs to be performed when character limits are exceeded?

OpenTelemetry is currently adding support for the tracestate and [this question came up there](https://github.com/open-telemetry/opentelemetry-go/pull/1340#discussion_r533796761) for context.

**Comment by dyladan** [comment]
The spec isn't clear here, but it would make sense to me that the behavior of truncating 128+ character entries first only applies to truncation due to byte size constraint. The 32 list-member limit should just drop the right-most key.

I agree the spec isn't clear here and it should be cleared up.
