### ISSUE TITLE
Should a tracestate key always be allowed to start with a lowercase letter or digit?

### ISSUE THREAD

**Issue by MrAlias** [w3c/trace-context#441]
The ABNF for the tracestate [key](https://www.w3.org/TR/trace-context-1/#key) is defined with the following.

```
key = lcalpha 0*255( lcalpha / DIGIT / "_" / "-"/ "*" / "/" )
key = ( lcalpha / DIGIT ) 0*240( lcalpha / DIGIT / "_" / "-"/ "*" / "/" ) "@" lcalpha 0*13( lcalpha / DIGIT / "_" / "-"/ "*" / "/" )
lcalpha    = %x61-7A ; a-z
```

However, the specification also states that the key can start with a lowercase letter or a digit.

> Identifiers MUST begin with a lowercase letter or a digit

My understanding of the first ABNF definition for the key states that it can only start with a lowercase letter, not a digit. Is this intentional, or should both forms of the definition allow for a key to start with a digit?

**Comment by dyladan** [comment]
I interpret this the same way. I don't know where this restriction comes from, or why it does not apply to tracestate vendored keys (with @ symbol).

**Comment by dyladan** [comment]
The test cases use the ABNF version
