### ISSUE TITLE
Expected behavior with regard to starting a trace should be spelled out explicitly

### ISSUE THREAD

**Issue by basti1302** [w3c/trace-context#442]
A bit of a follow up from #390 and #433 and discussions around that in the last workshop and meeting.

The spec does not explicitly spell out the expected behavior for tracers when no traceparent header is incoming. Should a tracer start a trace by creating a trace ID and send `traceparent` downstream? 

IMO, the current wording in the non-normative section kind of implies that tracers are actually expected to start a trace if no traceparent is incoming. But apparently the current consensus is that "a tracer SHOULD start a trace if no traceparent is incoming" is already too strong here. In which case we should make that consensus explicit, too. 

Maybe we could add something to the "If no traceparent header is received:" case.

**Comment by kalyanaj** [comment]
From Daniel: We can add additional information after SHOULD on an example where an implementation may not want to start a new trace.

**Comment by basti1302** [comment]
For the sake of completeness, as discussed, I'll try to summarizing earlier comments that were in opposition to the spec mandating always send headers downstream, even when no headers are incoming:

https://github.com/w3c/trace-context/pull/433#discussion_r513557193
>  IMO, i.e. the spec should not dictate starting a new trace. (Yury)

https://github.com/w3c/trace-context/pull/433#discussion_r513558998
> -1 to this addition. A component should be free to not send trace context downstream if there was non from upstream. (Yury)

https://github.com/w3c/trace-context/pull/433#discussion_r514572159
> There is a use case that even generating a new random ID is an extra unnecessary overhead for very high QPS services if the trace is not going to be sampled.

But: Those comments were made in the context of the question how a participant would propagate the decision to not sample downstream, so they are not really applicable directly here.

I will follow up with a PR to the effect that participants SHOULD start a trace and send headers downstream as suggested. Notable good reasons to not do it would then include performance considerations when the participant is not sampling this particular request.
