### ISSUE TITLE
Consider renaming parent-id / child-id to span-id

### ISSUE THREAD

**Issue by mwear** [w3c/trace-context#447]
The `traceparent` and `traceresponse` headers have identical formats, but use different names for the operation id (the 8-byte id). `traceparent` refers to `parent-id` and `traceresponse` refers to `child-id`. We could unify the formats by naming this `span-id` instead. Whether the span-id represents a parent or child can be inferred from the header.

These are the current definitions:

### traceparent
```abnf
version-format   = trace-id "-" parent-id "-" trace-flags
trace-id         = 32HEXDIGLC  ; 16 bytes array identifier. All zeroes forbidden
parent-id        = 16HEXDIGLC  ; 8 bytes array identifier. All zeroes forbidden
trace-flags      = 2HEXDIGLC   ; 8 bit flags. Currently, only one bit is used. See below for details
```

### traceresponse
``` abnf
version-format   = trace-id "-" child-id "-" trace-flags
trace-id         = 32HEXDIGLC  ; 16 bytes array identifier. All zeroes forbidden
child-id         = 16HEXDIGLC  ; 8 bytes array identifier. All zeroes forbidden
trace-flags      = 2HEXDIGLC   ; 8 bit flags. Currently, only one bit is used. See below for details
```

**Comment by dyladan** [comment]
As far as I'm aware "span" is OpenTelemetry terminology. Is this widely accepted enough terminology to use?

**Comment by SergeyKanzhelev** [comment]
See discussion here: https://github.com/w3c/trace-context/issues/205

**Comment by yurishkuro** [comment]
@mwear please clarify what the goal is, to avoid re-defining the format and just saying "traceresponse has the same format as traceparent except that the (span) id means something else?" 

I agree that "span" is not always applicable (I happen to work with a tracing platform right now that uses event model, not span model, similar to X-Trace, and the ID that's propagated cannot be considered "span id").

**Comment by mwear** [comment]
The goal is to have a generic way to refer to the constituents of a trace (e.g. spans, events, segments, operations, etc). We know that the trace-id is the id of the trace. We use the terms parent-id and child-id, but we don't say what the id represents (e.g. parent-(span | event | segment)-id). I realize that not all tracing systems will use the term span, but I am suggesting it as a commonly understood, but unambiguous way to refer to components of a trace. I'm open to other suggestions or maintaining the status quo.

**Comment by yurishkuro** [comment]
The term "tracepoint" is an approximation that can fit both span id in the span model and an event id in the event model. But it is not commonly used.

**Comment by mwear** [comment]
I might have underestimated how much of a can of worms this would be when opening this issue 😬.

**Comment by yurishkuro** [comment]
so much that it may be easier to repeat the format definition for each header and add a footnote that structurally they are identical :-)

**Comment by mwear** [comment]
Closing before this causes any more trouble.
