### ISSUE TITLE
Use of W3C Trace-Context with multiple agents in a single process, inject issue

### ISSUE THREAD

**Issue by pavolloffay** [w3c/trace-context#451]
From the field, we have seen several users running multiple agents in a single process (e.g. New Relic and OpenTelemetry). This usually happens during the evaluation phase but also in production e.g. Traceable provides a security agent so customers usually run Traceable alongside an APM solution.

Agents in a single process can use the same inter-process context propagation format (e.g. `traceparent`), which causes issues at context injection time - the most outbound instrumentation overrides previously injected headers.

This behavior caused an issue when using OpenTelemetry java instrumentation with New Relic agent. Both use W3C-Trace Context. The issue was caused in AWS SDK instrumentation. The OTEL instrumentation adds the traceparent header first, the header is used in AWS SDK to calculate a checksum. Then New Relic instrumentation overrides the header which invalidates checksum and causes all requests to fail. The OTEL instrumentation adds the headers early on purpose to include the `traceparent` in the checksum to prevent MITM attacks.

I cannot think of how multiple agents in a single process could use `traceparent` (with the current spec). The agents do not share any in-process state so they both start traces with different trace IDs and then try to inject them into the carrier. The spec could be extended for this use-case, but also it could define semantics what to do if there is already `traceparent` present in the headers (headers object in the process).

**Comment by danielkhan** [comment]
Double tracing is a known problem in monitoring scenarios and we came to the conclusion that there is no way the spec could mitigate this.
A solution could be to provide accessors to `tracestate` / `tracecontext` in OpenTelemetry. With this, other agents could default to it and make sure that they don't override existing tracing data.
The spec defines just the format and also interop in cases when two agents participate on a trace in different processes. In-process interoperability is something vendors have to tackle themselves.

**Comment by kamtschatka** [comment]
I was thinking about a similar issue and tried to find a solution for it.
Adding some extra code to OpenTelemetry will not solve this problem for every possible combination of 2 (or more) agents on the same page, so a general solution would be nice here.

Wouldn't it be possible to specify that wrappers need to wrap the setRequestHeader function, to be able to intercept any incoming tracecontext headers and use them for correlation?

This would be the scenario:
* OpenTelemetry creates the trace-parent header, calls setRequestHeader, the next wrapper(in your sample NewRelic) would NOT override the trace-parent header, but store somehow that the trace it created internally will actually use a different trace-parent header and just forwards the trace-parent header to the native XHR object.
* The same thing would also work if NewRelic would set the headers first and then OpenTelemetry would be required to reuse the existing headers created by NewRelic.

If every Vendor can agree on that, I guess we could solve this problem?

**Comment by SergeyKanzhelev** [comment]
@kamtschatka agreeing on headers reuse is a neat solution that may work in many cases. It can/should be specified in OpenTelemetry.

As @danielkhan said, this issues is not in scope of the specification.
