### ISSUE TITLE
Microsoft nominates new member as Chair

### ISSUE THREAD

**Issue by Kanwaldeep** [w3c/trace-context#453]
Microsoft nominates  J Kalyana Sundaram to be a chair W3C Trace Context community. Kalyana is Principal Software Engineer working in Microsoft for over 20 years. He is currently working as Architect for building platform for Distributed Tracing and also how we can integrating the tracing and metrics pillars of observabilities.

**Comment by danielkhan** [comment]
@caribouW3 please advice on the next formal steps.

**Comment by yurishkuro** [comment]
I am extrapolating from the OpenTelemetry election process, but I think it's relevant here as well: a nominee running for a role could provide a "campaign" statement ([examples][1]) explaining things like:
  * why do they want to be a chair?
  * why would the community want them to be a chair?
  * what is their history of participation in the project?

[1]: https://github.com/open-telemetry/community/blob/main/elections/2020/governance-committee-candidates.md

**Comment by caribouW3** [comment]
Hi,
Only the W3C management can appoint chairs. There is no point in raising an issue here, please
reach out to Philippe @plehegar by email.

To complete what Yuri said above, this page has useful information about a chair's role:
https://www.w3.org/Guide/chair/role.html.
