### ISSUE TITLE
Confusion between vendor and tenant in tracestate keys

### ISSUE THREAD

**Issue by taylor-hunt-kr** [w3c/trace-context#459]
[§ 3.3.1.3.1 Key](https://www.w3.org/TR/trace-context/#key):

> Vendors SHOULD set the tenant ID at the beginning of the key. For example,
`fw529a3039@dt` - `fw529a3039` is a tenant ID and `@dt` is a vendor name.

The example key seems to have the tenant ID at the _end_, not the beginning. Or am I missing something?

**Comment by SergeyKanzhelev** [comment]
Thank you! Also discussed we need to change dt to smething obviously meaningless as part of this errata

**Comment by dyladan** [comment]
This user is confused about the difference between "tenant" and "vendor." This is actually not an error. In the key `fw529a3039@dt`, the _vendor_ is `dt` but the _tenant_ is `fw529a3039`. The tenant ID in this case is at the beginning of the key.

I would suggest wording like this:

> In a distributed application where different components may be traced by different instances of the same multi-tenant tracing system, the system SHOULD keep the system ID at the end of the key. For example, `001@xyz` - `001` is a tenant ID and `xyz` is a vendor name.
