### ISSUE TITLE
Describe strategies used to work with sites who don't have fixed-width IDs

### ISSUE THREAD

**Issue by codefromthecrypt** [w3c/trace-context#6]
Predefined ID formats allows propagation and reporting to interoperate for the constraint of those who can fit their traceId and span Id into 128 and 64bits respectively. It also allows log correlation or 3rd parties to tokenize the IDs in understood ways. It does not help those who have different ID schemes (for example bread crumb ids, path ids etc).

Those who have other ID formats may be served by an exchange. For example, multi-tenant systems typically do not trust user created ids. They might accept an ID in the pre-specified format, link it to their internal IDs (which may or may not use the same format), carry it forward and potentially out of the system on the other side in the old format. Patterns like this could be enumerated and tested.

Other approaches could be to embed a signal into the ID format indicating it is not standard. Systems could make a "best effort" to join the trace, and define how they would fail when for example unicode is sent instead of hex. In many cases, tracing simply wouldn't work across these links, but we would be able to define what expected behavior could be.

This issue could serve as a brainstorming ground for how to ensure interop isn't compromised in aims to support systems that are not present at the moment.

**Comment by codefromthecrypt** [comment]
For those who haven't supported diverse users of a format before, there is a lot of history in B3 where people subtly encoded identifiers wrong, or in mysterious ways (such as prefixing with dictionary words). Usually they did this for lack of a specification, hence us reverse-engineering a [specification](https://github.com/openzipkin/b3-propagation) to meet that demand. By having at least one understood format we can prevent this spec from being worse than its predecessor for interop. We don't want to re-learn problems of the past.

That doesn't mean we can't experiment with concrete systems whose IDs don't match for whatever reason. Brown field systems like B3, X-Ray and others will for the foreseeable future continue with their formats even if this is also adopted.  Essentially, this issue is to explore ways this issue helps or not hurts those unwilling or unable to use this format or the ID constraints it defines.

**Comment by AloisReitbauer** [comment]
Tracestate should resolve this issue. This is why we are closing. Implementations can put their custom data there.
