### ISSUE TITLE
Charter Definition

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#60]
Subscribe this issue for updates on defining the charter

**Comment by AloisReitbauer** [comment]
I worked on the charter to have it ready for a first discussion with W3C.  Please have a look and provide feedback.

**Comment by AloisReitbauer** [comment]
Did not yet get any feedback. Are you all good to move forward?

**Comment by yurishkuro** [comment]
where is it?

**Comment by AloisReitbauer** [comment]
https://github.com/w3c/distributed-tracing/blob/master/charter.html

**Comment by SergeyKanzhelev** [comment]
Charter looks good for me. This link is better for user-friendly ready of the doc: https://w3c.github.io/distributed-tracing/charter.html

**Comment by wseltzer** [comment]
Steps in WG chartering, per the [W3C Process](https://www.w3.org/2018/Process-20180201/#GAGeneral):
* Advance notice of work in progress (propose to send that after teleconference Tuesday)
* W3C Management/Director approval of charter to send for Advisory Committee review
* 4-week Advisory Committee review: groups are expected to get 5% of W3C membership support (~22)
* Director review of any comments/resolution of any objections

**Comment by wseltzer** [comment]
Some questions about the draft charter: 
* what links should be filled in for the starting documents? 
* trace context timelines don't match between "expected completion" Q4 2018 (2.1) and Dec. 2018 CR (2.3). December CR sounds more realistic, which would put expected completion of the Rec to, say, Q2 2019. 
* Many W3C groups use 2 interoperable implementations as the exit criteria. Are you deliberately setting the bar higher at 3?

**Comment by codefromthecrypt** [comment]
>
>
>    - Many W3C groups use 2 interoperable implementations as the exit
>    criteria. Are you deliberately setting the bar higher at 3?
>
> I didn't write this part, but due to the number of clones and forks of
technology, more than two systems already are interoperable without this
spec.

I like that the bar is a bit higher, and would love to see 5 actually, and
some things like tools made in different foundations (ex CNCF and Apache),
or 2+ public services with $1B+ revenue.

a bit crazy, but anyway 3 is fine, too :P

**Comment by AloisReitbauer** [comment]
For trace-context we already have a link to the current draft. Will add it to the docs. Same for correlation context.
Regarding timelines. Thank you for catching this will fix it.

**Comment by AloisReitbauer** [comment]
Regarding implementations:

I moved the bar higher here :-). Defining a standard for interoperability that is only implemented by two vendors, while there are about 10 more or less widely used products out there feels a bit low. Just at the current state, I see up to 5 implementations supporting trace-context.

**Comment by wseltzer** [comment]
Another important aspect: IP commitments on the input documents. We can get those via [CG Final Specification Agreement](https://www.w3.org/community/about/agreements/final/)

**Comment by AloisReitbauer** [comment]
Closing the issue for now. Based on feedback we will adjust the charter going forward.
