### ISSUE TITLE
List all the libraries that are willing to use this format

### ISSUE THREAD

**Issue by rakyll** [w3c/trace-context#7]
#4 seems to be reserved for the backend support, I am creating this issue to track the library work.

The Go programming language wants to introduce a trace package and implement this spec. We were considering about establishing our own data format to be able to instrument the standard library internally, and convert tracing systems’ to our format back and forth to be able to traces started outside of Go code. A standard will help us a lot to be able to compatible with the rest of the world without doing the ugly and expensive conversion work.

Some of our possible future items :

* net/http.Handler will be able to automatically extract incoming traces, net/http.Transport will inject traces into the outgoing requests.
* database/sql will create spans for ExecContext.
* Go libraries will be able to propagate traces via context.Context.
* Go libraries will be able to instrument code without external dependencies.

**Comment by wu-sheng** [comment]
:+1:

**Comment by AloisReitbauer** [comment]
I think, we need to create some sort of automated test cases to verify whether libraries are compliant. This list will get very long.

**Comment by codefromthecrypt** [comment]
Heh i think if you create a complaince test it might make it short ;)

**Comment by AloisReitbauer** [comment]
Closing this one, as we currently have no idea how to test this.
