### ISSUE TITLE
Should there be a recommendation on how trace IDs are generated?

### ISSUE THREAD

**Issue by yurishkuro** [w3c/trace-context#79]
This was raised in Jaeger [here](https://github.com/jaegertracing/jaeger-client-java/issues/318#issuecomment-371843638), but it seems like an interesting aspect if we expect different tracing systems to share the same trace ID.

Is [RFC 4122](https://tools.ietf.org/html/rfc4122.html) way of generating UUIDs good enough for tracing purposes? Or is it better to use fully random IDs?

**Comment by wu-sheng** [comment]
I have the same question. :+1:  Thanks @yurishkuro

**Comment by codefromthecrypt** [comment]
right now trace context doesn't really imply sharing a trace id across
different systems.

Based on practical concerns many libraries are adopting epoch32 followed by
92bit random trace ID. But in this case there is shared knowledge about the
tracing system (ex the key name for the trace state would be the same)

**Comment by AloisReitbauer** [comment]
I would only agree on limitations for data format. Regarding UUIDs, we had rare cases when we saw clashed of UUIDs.

**Comment by odeke-em** [comment]
An influence of one of the exporters for the OpenCensus project is AWS' XRay which uses a 32bit timestamp of the UNIX Epoch and then 96bits of randomness giving the form:
 `<version>-<4bytes_of_epoch_time>-<12bytes_of_randomness>`.

There is currently an open request for the Go implementation to change the way TraceIDs are generated, as per https://github.com/census-instrumentation/opencensus-go/issues/489
/cc @ramonza @savaki

**Comment by AloisReitbauer** [comment]
I think this is out-of-scope for now. As trace providers have very different requirements what information they need, I don't this is practical. 

What would be the advantage of a unified format. We are treating them as a blog anyways.

I would close this one.

**Comment by yurishkuro** [comment]
no objection to close

**Comment by AloisReitbauer** [comment]
Closing for now. Let's us revisit later
