### ISSUE TITLE
Find alternative meeting time

### ISSUE THREAD

**Issue by AloisReitbauer** [w3c/trace-context#92]
As discussed in the last meeting, we want to alternate meeting times.  I used meetingplanner [1] to show what good and bad times there are for meetings. Unfortunately, there is no good time for all of us. 

Overall this seems be an np-hard problem to solve. Here is what I did. I removed all meetings that are between midnight and 6:00 a.m. in any timezone. This gets you the following list. 

UTC-time | San Francisco | Brooklyn | Linz | Kuala Lumpur
-- | -- | -- | -- | --
Tuesday, April 3,   2018 at 13:00:00 | Tue 6:00 am * | Tue 9:00 am * | Tue 3:00 pm * | Tue 9:00 pm
Tuesday, April 3,   2018 at 13:30:00 | Tue 6:30 am * | Tue 9:30 am * | Tue 3:30 pm * | Tue 9:30 pm
Tuesday, April 3,   2018 at 14:00:00 | Tue 7:00 am * | Tue 10:00 am * | Tue 4:00 pm * | Tue 10:00 pm
Tuesday, April 3,   2018 at 14:30:00 | Tue 7:30 am * | Tue 10:30 am * | Tue 4:30 pm * | Tue 10:30 pm
Tuesday, April 3,   2018 at 15:00:00 | Tue 8:00 am * | Tue 11:00 am * | Tue 5:00 pm * | Tue 11:00 pm
Tuesday, April 3,   2018 at 15:30:00 | Tue 8:30 am * | Tue 11:30 am * | Tue 5:30 pm * | Tue 11:30 pm

[1] https://www.timeanddate.com/worldclock/meetingtime.html?month=4&day=3&year=2018&p1=224&p2=4826&p3=319&p4=122&iv=1800

**Comment by SergeyKanzhelev** [comment]
I'm OK with 8 AM or 8:30 AM PST (San Francisco). I'm also fine with what we have today - 2 PM PST.

**Comment by SergeyKanzhelev** [comment]
@AloisReitbauer suggests 9 or 10 AM PST.



| UTC-time | San Francisco | Brooklyn | Linz | Kuala Lumpur |
|------------------------------------|----------------|------------------|---------------|--------------------|
| Tuesday, April 3, 2018 at 16:00:00 | Tue 9:00 am * | Tue 12:00 noon * | Tue 6:00 pm * | Wed 12:00 midnight |
| Tuesday, April 3, 2018 at 16:30:00 | Tue 9:30 am * | Tue 12:30 pm * | Tue 6:30 pm * | Wed 12:30 am |
| Tuesday, April 3, 2018 at 17:00:00 | Tue 10:00 am * | Tue 1:00 pm * | Tue 7:00 pm * | Wed 1:00 am |
|  |  |  |  |  |

**Comment by codefromthecrypt** [comment]
For the record, a suggestion I made once was to have rotating synchronous
meetings which don't expect the entire earth to be present at all meetings.

This stops the unrealistic expectation that folks in non-bay area timezones
will routinely show up at off hours.

I know this suggestion was rejected and matters less to me personally as I
am unlikely to attend. However, as this is a spec for the earth, it would
be nice to consider this even if to reject it again.

**Comment by AloisReitbauer** [comment]
We have an updated meeting time.
