### ISSUE TITLE
Is the W3C 3-clause BSD License acceptable for integration tests? 

### ISSUE THREAD

**Issue by yurishkuro** [w3c/trace-context#94]
the LICENSE file says: 

> Contributions to Test Suites are made under the [W3C 3-clause BSD License](https://www.w3.org/Consortium/Legal/2008/03-bsd-license.html)

Is this going to be a problem for vendors who want to submit something to run in the official tests? Why can't we use Apache 2 license?

**Comment by SergeyKanzhelev** [comment]
@wseltzer can you comment on this?

**Comment by wseltzer** [comment]
Sorry for missing this earlier. If you're planning to put tests into the Web Platform Tests, then consistency with what's already there, https://github.com/w3c/web-platform-tests/blob/master/LICENSE.md  would be important. If you're planning otherwise, we can ask the Director about using Apache 2 instead. Can you share more about why vendors might prefer Apache 2, @yurishkuro ?

**Comment by yurishkuro** [comment]
@adriancole I recall you had some strong arguments in the past for Apache 2 vs. MIT-style license.

I am checking with Uber's legal, but I think BSD-3 will be ok.

@wseltzer I don't think we're planning to put trace context test suite under web-platform-tests. Purely from implementation point of view, the test suite is implemented in Go and uses Docker containers, which doesn't seem to fit the requirements of web-platform-tests.

**Comment by codefromthecrypt** [comment]
ASL tends to be the least questions asked, which leads to least roadblock
choice. That's why we universally use it in Zipkin for example.

**Comment by wseltzer** [comment]
Ok, I'll ask for the Director approval.

**Comment by SergeyKanzhelev** [comment]
In #87 we discussing that test cases will mostly operate on http endpoint and not manage the target container. We also plan to contribute test cases as unit tests. Thus we do not need top take a dependency on any components with the different license. Closing issue for now
